# encoding: utf-8
from colors_classifier.colors import Color


# pallete of 16 commonly used web colors
# in accordance to HTML 4.01
# (http://en.wikipedia.org/wiki/Web_colors)
WEB_PALETTE = {
    "white":    Color.from_hex("#FFFFFF"),
    "silver":   Color.from_hex("#C0C0C0"),
    "gray":     Color.from_hex("#808080"),
    "black":    Color.from_hex("#000000"),
    "red":      Color.from_hex("#FF0000"),
    "maroon":   Color.from_hex("#800000"),
    "yellow":   Color.from_hex("#FFFF00"),
    "olive":    Color.from_hex("#808000"),
    "lime":     Color.from_hex("#00FF00"),
    "green":    Color.from_hex("#008000"),
    "aqua":     Color.from_hex("#00FFFF"),
    "teal":     Color.from_hex("#008080"),
    "blue":     Color.from_hex("#0000FF"),
    "navy":     Color.from_hex("#000080"),
    "fuchsia":  Color.from_hex("#FF00FF"),
    "purple":   Color.from_hex("#800080")
}


# palette created as a result of survey
# published by xkcd: http://blog.xkcd.com/2010/05/03/color-survey-results/
XKCD_FULL_PALETTE = {
    "cloudy blue":    Color.from_hex("#ACC2D9"),
    "dark pastel green":    Color.from_hex("#56AE57"),
    "dust":    Color.from_hex("#B2996E"),
    "electric lime":    Color.from_hex("#A8FF04"),
    "fresh green":    Color.from_hex("#69D84F"),
    "light eggplant":    Color.from_hex("#894585"),
    "nasty green":    Color.from_hex("#70B23F"),
    "really light blue":    Color.from_hex("#D4FFFF"),
    "tea":    Color.from_hex("#65AB7C"),
    "warm purple":    Color.from_hex("#952E8F"),
    "yellowish tan":    Color.from_hex("#FCFC81"),
    "cement":    Color.from_hex("#A5A391"),
    "dark grass green":    Color.from_hex("#388004"),
    "dusty teal":    Color.from_hex("#4C9085"),
    "grey teal":    Color.from_hex("#5E9B8A"),
    "macaroni and cheese":    Color.from_hex("#EFB435"),
    "pinkish tan":    Color.from_hex("#D99B82"),
    "spruce":    Color.from_hex("#0A5F38"),
    "strong blue":    Color.from_hex("#0C06F7"),
    "toxic green":    Color.from_hex("#61DE2A"),
    "windows blue":    Color.from_hex("#3778BF"),
    "blue blue":    Color.from_hex("#2242C7"),
    "blue with a hint of purple":    Color.from_hex("#533CC6"),
    "booger":    Color.from_hex("#9BB53C"),
    "bright sea green":    Color.from_hex("#05FFA6"),
    "dark green blue":    Color.from_hex("#1F6357"),
    "deep turquoise":    Color.from_hex("#017374"),
    "green teal":    Color.from_hex("#0CB577"),
    "strong pink":    Color.from_hex("#FF0789"),
    "bland":    Color.from_hex("#AFA88B"),
    "deep aqua":    Color.from_hex("#08787F"),
    "lavender pink":    Color.from_hex("#DD85D7"),
    "light moss green":    Color.from_hex("#A6C875"),
    "light seafoam green":    Color.from_hex("#A7FFB5"),
    "olive yellow":    Color.from_hex("#C2B709"),
    "pig pink":    Color.from_hex("#E78EA5"),
    "deep lilac":    Color.from_hex("#966EBD"),
    "desert":    Color.from_hex("#CCAD60"),
    "dusty lavender":    Color.from_hex("#AC86A8"),
    "purpley grey":    Color.from_hex("#947E94"),
    "purply":    Color.from_hex("#983FB2"),
    "candy pink":    Color.from_hex("#FF63E9"),
    "light pastel green":    Color.from_hex("#B2FBA5"),
    "boring green":    Color.from_hex("#63B365"),
    "kiwi green":    Color.from_hex("#8EE53F"),
    "light grey green":    Color.from_hex("#B7E1A1"),
    "orange pink":    Color.from_hex("#FF6F52"),
    "tea green":    Color.from_hex("#BDF8A3"),
    "very light brown":    Color.from_hex("#D3B683"),
    "egg shell":    Color.from_hex("#FFFCC4"),
    "eggplant purple":    Color.from_hex("#430541"),
    "powder pink":    Color.from_hex("#FFB2D0"),
    "reddish grey":    Color.from_hex("#997570"),
    "baby shit brown":    Color.from_hex("#AD900D"),
    "liliac":    Color.from_hex("#C48EFD"),
    "stormy blue":    Color.from_hex("#507B9C"),
    "ugly brown":    Color.from_hex("#7D7103"),
    "custard":    Color.from_hex("#FFFD78"),
    "darkish pink":    Color.from_hex("#DA467D"),
    "deep brown":    Color.from_hex("#410200"),
    "greenish beige":    Color.from_hex("#C9D179"),
    "manilla":    Color.from_hex("#FFFA86"),
    "off blue":    Color.from_hex("#5684AE"),
    "battleship grey":    Color.from_hex("#6B7C85"),
    "browny green":    Color.from_hex("#6F6C0A"),
    "bruise":    Color.from_hex("#7E4071"),
    "kelley green":    Color.from_hex("#009337"),
    "sickly yellow":    Color.from_hex("#D0E429"),
    "sunny yellow":    Color.from_hex("#FFF917"),
    "azul":    Color.from_hex("#1D5DEC"),
    "darkgreen":    Color.from_hex("#054907"),
    "green/yellow":    Color.from_hex("#B5CE08"),
    "lichen":    Color.from_hex("#8FB67B"),
    "light light green":    Color.from_hex("#C8FFB0"),
    "pale gold":    Color.from_hex("#FDDE6C"),
    "sun yellow":    Color.from_hex("#FFDF22"),
    "tan green":    Color.from_hex("#A9BE70"),
    "burple":    Color.from_hex("#6832E3"),
    "butterscotch":    Color.from_hex("#FDB147"),
    "toupe":    Color.from_hex("#C7AC7D"),
    "dark cream":    Color.from_hex("#FFF39A"),
    "indian red":    Color.from_hex("#850E04"),
    "light lavendar":    Color.from_hex("#EFC0FE"),
    "poison green":    Color.from_hex("#40FD14"),
    "baby puke green":    Color.from_hex("#B6C406"),
    "bright yellow green":    Color.from_hex("#9DFF00"),
    "charcoal grey":    Color.from_hex("#3C4142"),
    "squash":    Color.from_hex("#F2AB15"),
    "cinnamon":    Color.from_hex("#AC4F06"),
    "light pea green":    Color.from_hex("#C4FE82"),
    "radioactive green":    Color.from_hex("#2CFA1F"),
    "raw sienna":    Color.from_hex("#9A6200"),
    "baby purple":    Color.from_hex("#CA9BF7"),
    "cocoa":    Color.from_hex("#875F42"),
    "light royal blue":    Color.from_hex("#3A2EFE"),
    "orangeish":    Color.from_hex("#FD8D49"),
    "rust brown":    Color.from_hex("#8B3103"),
    "sand brown":    Color.from_hex("#CBA560"),
    "swamp":    Color.from_hex("#698339"),
    "tealish green":    Color.from_hex("#0CDC73"),
    "burnt siena":    Color.from_hex("#B75203"),
    "camo":    Color.from_hex("#7F8F4E"),
    "dusk blue":    Color.from_hex("#26538D"),
    "fern":    Color.from_hex("#63A950"),
    "old rose":    Color.from_hex("#C87F89"),
    "pale light green":    Color.from_hex("#B1FC99"),
    "peachy pink":    Color.from_hex("#FF9A8A"),
    "rosy pink":    Color.from_hex("#F6688E"),
    "light bluish green":    Color.from_hex("#76FDA8"),
    "light bright green":    Color.from_hex("#53FE5C"),
    "light neon green":    Color.from_hex("#4EFD54"),
    "light seafoam":    Color.from_hex("#A0FEBF"),
    "tiffany blue":    Color.from_hex("#7BF2DA"),
    "washed out green":    Color.from_hex("#BCF5A6"),
    "browny orange":    Color.from_hex("#CA6B02"),
    "nice blue":    Color.from_hex("#107AB0"),
    "sapphire":    Color.from_hex("#2138AB"),
    "greyish teal":    Color.from_hex("#719F91"),
    "orangey yellow":    Color.from_hex("#FDB915"),
    "parchment":    Color.from_hex("#FEFCAF"),
    "straw":    Color.from_hex("#FCF679"),
    "very dark brown":    Color.from_hex("#1D0200"),
    "terracota":    Color.from_hex("#CB6843"),
    "ugly blue":    Color.from_hex("#31668A"),
    "clear blue":    Color.from_hex("#247AFD"),
    "creme":    Color.from_hex("#FFFFB6"),
    "foam green":    Color.from_hex("#90FDA9"),
    "grey/green":    Color.from_hex("#86A17D"),
    "light gold":    Color.from_hex("#FDDC5C"),
    "seafoam blue":    Color.from_hex("#78D1B6"),
    "topaz":    Color.from_hex("#13BBAF"),
    "violet pink":    Color.from_hex("#FB5FFC"),
    "wintergreen":    Color.from_hex("#20F986"),
    "yellow tan":    Color.from_hex("#FFE36E"),
    "dark fuchsia":    Color.from_hex("#9D0759"),
    "indigo blue":    Color.from_hex("#3A18B1"),
    "light yellowish green":    Color.from_hex("#C2FF89"),
    "pale magenta":    Color.from_hex("#D767AD"),
    "rich purple":    Color.from_hex("#720058"),
    "sunflower yellow":    Color.from_hex("#FFDA03"),
    "green/blue":    Color.from_hex("#01C08D"),
    "leather":    Color.from_hex("#AC7434"),
    "racing green":    Color.from_hex("#014600"),
    "vivid purple":    Color.from_hex("#9900FA"),
    "dark royal blue":    Color.from_hex("#02066F"),
    "hazel":    Color.from_hex("#8E7618"),
    "muted pink":    Color.from_hex("#D1768F"),
    "booger green":    Color.from_hex("#96B403"),
    "canary":    Color.from_hex("#FDFF63"),
    "cool grey":    Color.from_hex("#95A3A6"),
    "dark taupe":    Color.from_hex("#7F684E"),
    "darkish purple":    Color.from_hex("#751973"),
    "true green":    Color.from_hex("#089404"),
    "coral pink":    Color.from_hex("#FF6163"),
    "dark sage":    Color.from_hex("#598556"),
    "dark slate blue":    Color.from_hex("#214761"),
    "flat blue":    Color.from_hex("#3C73A8"),
    "mushroom":    Color.from_hex("#BA9E88"),
    "rich blue":    Color.from_hex("#021BF9"),
    "dirty purple":    Color.from_hex("#734A65"),
    "greenblue":    Color.from_hex("#23C48B"),
    "icky green":    Color.from_hex("#8FAE22"),
    "light khaki":    Color.from_hex("#E6F2A2"),
    "warm blue":    Color.from_hex("#4B57DB"),
    "dark hot pink":    Color.from_hex("#D90166"),
    "deep sea blue":    Color.from_hex("#015482"),
    "carmine":    Color.from_hex("#9D0216"),
    "dark yellow green":    Color.from_hex("#728F02"),
    "pale peach":    Color.from_hex("#FFE5AD"),
    "plum purple":    Color.from_hex("#4E0550"),
    "golden rod":    Color.from_hex("#F9BC08"),
    "neon red":    Color.from_hex("#FF073A"),
    "old pink":    Color.from_hex("#C77986"),
    "very pale blue":    Color.from_hex("#D6FFFE"),
    "blood orange":    Color.from_hex("#FE4B03"),
    "grapefruit":    Color.from_hex("#FD5956"),
    "sand yellow":    Color.from_hex("#FCE166"),
    "clay brown":    Color.from_hex("#B2713D"),
    "dark blue grey":    Color.from_hex("#1F3B4D"),
    "flat green":    Color.from_hex("#699D4C"),
    "light green blue":    Color.from_hex("#56FCA2"),
    "warm pink":    Color.from_hex("#FB5581"),
    "dodger blue":    Color.from_hex("#3E82FC"),
    "gross green":    Color.from_hex("#A0BF16"),
    "ice":    Color.from_hex("#D6FFFA"),
    "metallic blue":    Color.from_hex("#4F738E"),
    "pale salmon":    Color.from_hex("#FFB19A"),
    "sap green":    Color.from_hex("#5C8B15"),
    "algae":    Color.from_hex("#54AC68"),
    "bluey grey":    Color.from_hex("#89A0B0"),
    "greeny grey":    Color.from_hex("#7EA07A"),
    "highlighter green":    Color.from_hex("#1BFC06"),
    "light light blue":    Color.from_hex("#CAFFFB"),
    "light mint":    Color.from_hex("#B6FFBB"),
    "raw umber":    Color.from_hex("#A75E09"),
    "vivid blue":    Color.from_hex("#152EFF"),
    "deep lavender":    Color.from_hex("#8D5EB7"),
    "dull teal":    Color.from_hex("#5F9E8F"),
    "light greenish blue":    Color.from_hex("#63F7B4"),
    "mud green":    Color.from_hex("#606602"),
    "pinky":    Color.from_hex("#FC86AA"),
    "red wine":    Color.from_hex("#8C0034"),
    "shit green":    Color.from_hex("#758000"),
    "tan brown":    Color.from_hex("#AB7E4C"),
    "darkblue":    Color.from_hex("#030764"),
    "rosa":    Color.from_hex("#FE86A4"),
    "lipstick":    Color.from_hex("#D5174E"),
    "pale mauve":    Color.from_hex("#FED0FC"),
    "claret":    Color.from_hex("#680018"),
    "dandelion":    Color.from_hex("#FEDF08"),
    "orangered":    Color.from_hex("#FE420F"),
    "poop green":    Color.from_hex("#6F7C00"),
    "ruby":    Color.from_hex("#CA0147"),
    "dark":    Color.from_hex("#1B2431"),
    "greenish turquoise":    Color.from_hex("#00FBB0"),
    "pastel red":    Color.from_hex("#DB5856"),
    "piss yellow":    Color.from_hex("#DDD618"),
    "bright cyan":    Color.from_hex("#41FDFE"),
    "dark coral":    Color.from_hex("#CF524E"),
    "algae green":    Color.from_hex("#21C36F"),
    "darkish red":    Color.from_hex("#A90308"),
    "reddy brown":    Color.from_hex("#6E1005"),
    "blush pink":    Color.from_hex("#FE828C"),
    "camouflage green":    Color.from_hex("#4B6113"),
    "lawn green":    Color.from_hex("#4DA409"),
    "putty":    Color.from_hex("#BEAE8A"),
    "vibrant blue":    Color.from_hex("#0339F8"),
    "dark sand":    Color.from_hex("#A88F59"),
    "purple/blue":    Color.from_hex("#5D21D0"),
    "saffron":    Color.from_hex("#FEB209"),
    "twilight":    Color.from_hex("#4E518B"),
    "warm brown":    Color.from_hex("#964E02"),
    "bluegrey":    Color.from_hex("#85A3B2"),
    "bubble gum pink":    Color.from_hex("#FF69AF"),
    "duck egg blue":    Color.from_hex("#C3FBF4"),
    "greenish cyan":    Color.from_hex("#2AFEB7"),
    "petrol":    Color.from_hex("#005F6A"),
    "royal":    Color.from_hex("#0C1793"),
    "butter":    Color.from_hex("#FFFF81"),
    "dusty orange":    Color.from_hex("#F0833A"),
    "off yellow":    Color.from_hex("#F1F33F"),
    "pale olive green":    Color.from_hex("#B1D27B"),
    "orangish":    Color.from_hex("#FC824A"),
    "leaf":    Color.from_hex("#71AA34"),
    "light blue grey":    Color.from_hex("#B7C9E2"),
    "dried blood":    Color.from_hex("#4B0101"),
    "lightish purple":    Color.from_hex("#A552E6"),
    "rusty red":    Color.from_hex("#AF2F0D"),
    "lavender blue":    Color.from_hex("#8B88F8"),
    "light grass green":    Color.from_hex("#9AF764"),
    "light mint green":    Color.from_hex("#A6FBB2"),
    "sunflower":    Color.from_hex("#FFC512"),
    "velvet":    Color.from_hex("#750851"),
    "brick orange":    Color.from_hex("#C14A09"),
    "lightish red":    Color.from_hex("#FE2F4A"),
    "pure blue":    Color.from_hex("#0203E2"),
    "twilight blue":    Color.from_hex("#0A437A"),
    "violet red":    Color.from_hex("#A50055"),
    "yellowy brown":    Color.from_hex("#AE8B0C"),
    "carnation":    Color.from_hex("#FD798F"),
    "muddy yellow":    Color.from_hex("#BFAC05"),
    "dark seafoam green":    Color.from_hex("#3EAF76"),
    "deep rose":    Color.from_hex("#C74767"),
    "dusty red":    Color.from_hex("#B9484E"),
    "grey/blue":    Color.from_hex("#647D8E"),
    "lemon lime":    Color.from_hex("#BFFE28"),
    "purple/pink":    Color.from_hex("#D725DE"),
    "brown yellow":    Color.from_hex("#B29705"),
    "purple brown":    Color.from_hex("#673A3F"),
    "wisteria":    Color.from_hex("#A87DC2"),
    "banana yellow":    Color.from_hex("#FAFE4B"),
    "lipstick red":    Color.from_hex("#C0022F"),
    "water blue":    Color.from_hex("#0E87CC"),
    "brown grey":    Color.from_hex("#8D8468"),
    "vibrant purple":    Color.from_hex("#AD03DE"),
    "baby green":    Color.from_hex("#8CFF9E"),
    "barf green":    Color.from_hex("#94AC02"),
    "eggshell blue":    Color.from_hex("#C4FFF7"),
    "sandy yellow":    Color.from_hex("#FDEE73"),
    "cool green":    Color.from_hex("#33B864"),
    "pale":    Color.from_hex("#FFF9D0"),
    "blue/grey":    Color.from_hex("#758DA3"),
    "hot magenta":    Color.from_hex("#F504C9"),
    "greyblue":    Color.from_hex("#77A1B5"),
    "purpley":    Color.from_hex("#8756E4"),
    "baby shit green":    Color.from_hex("#889717"),
    "brownish pink":    Color.from_hex("#C27E79"),
    "dark aquamarine":    Color.from_hex("#017371"),
    "diarrhea":    Color.from_hex("#9F8303"),
    "light mustard":    Color.from_hex("#F7D560"),
    "pale sky blue":    Color.from_hex("#BDF6FE"),
    "turtle green":    Color.from_hex("#75B84F"),
    "bright olive":    Color.from_hex("#9CBB04"),
    "dark grey blue":    Color.from_hex("#29465B"),
    "greeny brown":    Color.from_hex("#696006"),
    "lemon green":    Color.from_hex("#ADF802"),
    "light periwinkle":    Color.from_hex("#C1C6FC"),
    "seaweed green":    Color.from_hex("#35AD6B"),
    "sunshine yellow":    Color.from_hex("#FFFD37"),
    "ugly purple":    Color.from_hex("#A442A0"),
    "medium pink":    Color.from_hex("#F36196"),
    "puke brown":    Color.from_hex("#947706"),
    "very light pink":    Color.from_hex("#FFF4F2"),
    "viridian":    Color.from_hex("#1E9167"),
    "bile":    Color.from_hex("#B5C306"),
    "faded yellow":    Color.from_hex("#FEFF7F"),
    "very pale green":    Color.from_hex("#CFFDBC"),
    "vibrant green":    Color.from_hex("#0ADD08"),
    "bright lime":    Color.from_hex("#87FD05"),
    "spearmint":    Color.from_hex("#1EF876"),
    "light aquamarine":    Color.from_hex("#7BFDC7"),
    "light sage":    Color.from_hex("#BCECAC"),
    "yellowgreen":    Color.from_hex("#BBF90F"),
    "baby poo":    Color.from_hex("#AB9004"),
    "dark seafoam":    Color.from_hex("#1FB57A"),
    "deep teal":    Color.from_hex("#00555A"),
    "heather":    Color.from_hex("#A484AC"),
    "rust orange":    Color.from_hex("#C45508"),
    "dirty blue":    Color.from_hex("#3F829D"),
    "fern green":    Color.from_hex("#548D44"),
    "bright lilac":    Color.from_hex("#C95EFB"),
    "weird green":    Color.from_hex("#3AE57F"),
    "peacock blue":    Color.from_hex("#016795"),
    "avocado green":    Color.from_hex("#87A922"),
    "faded orange":    Color.from_hex("#F0944D"),
    "grape purple":    Color.from_hex("#5D1451"),
    "hot green":    Color.from_hex("#25FF29"),
    "lime yellow":    Color.from_hex("#D0FE1D"),
    "mango":    Color.from_hex("#FFA62B"),
    "shamrock":    Color.from_hex("#01B44C"),
    "bubblegum":    Color.from_hex("#FF6CB5"),
    "purplish brown":    Color.from_hex("#6B4247"),
    "vomit yellow":    Color.from_hex("#C7C10C"),
    "pale cyan":    Color.from_hex("#B7FFFA"),
    "key lime":    Color.from_hex("#AEFF6E"),
    "tomato red":    Color.from_hex("#EC2D01"),
    "lightgreen":    Color.from_hex("#76FF7B"),
    "merlot":    Color.from_hex("#730039"),
    "night blue":    Color.from_hex("#040348"),
    "purpleish pink":    Color.from_hex("#DF4EC8"),
    "apple":    Color.from_hex("#6ECB3C"),
    "baby poop green":    Color.from_hex("#8F9805"),
    "green apple":    Color.from_hex("#5EDC1F"),
    "heliotrope":    Color.from_hex("#D94FF5"),
    "yellow/green":    Color.from_hex("#C8FD3D"),
    "almost black":    Color.from_hex("#070D0D"),
    "cool blue":    Color.from_hex("#4984B8"),
    "leafy green":    Color.from_hex("#51B73B"),
    "mustard brown":    Color.from_hex("#AC7E04"),
    "dusk":    Color.from_hex("#4E5481"),
    "dull brown":    Color.from_hex("#876E4B"),
    "frog green":    Color.from_hex("#58BC08"),
    "vivid green":    Color.from_hex("#2FEF10"),
    "bright light green":    Color.from_hex("#2DFE54"),
    "fluro green":    Color.from_hex("#0AFF02"),
    "kiwi":    Color.from_hex("#9CEF43"),
    "seaweed":    Color.from_hex("#18D17B"),
    "navy green":    Color.from_hex("#35530A"),
    "ultramarine blue":    Color.from_hex("#1805DB"),
    "iris":    Color.from_hex("#6258C4"),
    "pastel orange":    Color.from_hex("#FF964F"),
    "yellowish orange":    Color.from_hex("#FFAB0F"),
    "perrywinkle":    Color.from_hex("#8F8CE7"),
    "tealish":    Color.from_hex("#24BCA8"),
    "dark plum":    Color.from_hex("#3F012C"),
    "pear":    Color.from_hex("#CBF85F"),
    "pinkish orange":    Color.from_hex("#FF724C"),
    "midnight purple":    Color.from_hex("#280137"),
    "light urple":    Color.from_hex("#B36FF6"),
    "dark mint":    Color.from_hex("#48C072"),
    "greenish tan":    Color.from_hex("#BCCB7A"),
    "light burgundy":    Color.from_hex("#A8415B"),
    "turquoise blue":    Color.from_hex("#06B1C4"),
    "ugly pink":    Color.from_hex("#CD7584"),
    "sandy":    Color.from_hex("#F1DA7A"),
    "electric pink":    Color.from_hex("#FF0490"),
    "muted purple":    Color.from_hex("#805B87"),
    "mid green":    Color.from_hex("#50A747"),
    "greyish":    Color.from_hex("#A8A495"),
    "neon yellow":    Color.from_hex("#CFFF04"),
    "banana":    Color.from_hex("#FFFF7E"),
    "carnation pink":    Color.from_hex("#FF7FA7"),
    "tomato":    Color.from_hex("#EF4026"),
    "sea":    Color.from_hex("#3C9992"),
    "muddy brown":    Color.from_hex("#886806"),
    "turquoise green":    Color.from_hex("#04F489"),
    "buff":    Color.from_hex("#FEF69E"),
    "fawn":    Color.from_hex("#CFAF7B"),
    "muted blue":    Color.from_hex("#3B719F"),
    "pale rose":    Color.from_hex("#FDC1C5"),
    "dark mint green":    Color.from_hex("#20C073"),
    "amethyst":    Color.from_hex("#9B5FC0"),
    "blue/green":    Color.from_hex("#0F9B8E"),
    "chestnut":    Color.from_hex("#742802"),
    "sick green":    Color.from_hex("#9DB92C"),
    "pea":    Color.from_hex("#A4BF20"),
    "rusty orange":    Color.from_hex("#CD5909"),
    "stone":    Color.from_hex("#ADA587"),
    "rose red":    Color.from_hex("#BE013C"),
    "pale aqua":    Color.from_hex("#B8FFEB"),
    "deep orange":    Color.from_hex("#DC4D01"),
    "earth":    Color.from_hex("#A2653E"),
    "mossy green":    Color.from_hex("#638B27"),
    "grassy green":    Color.from_hex("#419C03"),
    "pale lime green":    Color.from_hex("#B1FF65"),
    "light grey blue":    Color.from_hex("#9DBCD4"),
    "pale grey":    Color.from_hex("#FDFDFE"),
    "asparagus":    Color.from_hex("#77AB56"),
    "blueberry":    Color.from_hex("#464196"),
    "purple red":    Color.from_hex("#990147"),
    "pale lime":    Color.from_hex("#BEFD73"),
    "greenish teal":    Color.from_hex("#32BF84"),
    "caramel":    Color.from_hex("#AF6F09"),
    "deep magenta":    Color.from_hex("#A0025C"),
    "light peach":    Color.from_hex("#FFD8B1"),
    "milk chocolate":    Color.from_hex("#7F4E1E"),
    "ocher":    Color.from_hex("#BF9B0C"),
    "off green":    Color.from_hex("#6BA353"),
    "purply pink":    Color.from_hex("#F075E6"),
    "lightblue":    Color.from_hex("#7BC8F6"),
    "dusky blue":    Color.from_hex("#475F94"),
    "golden":    Color.from_hex("#F5BF03"),
    "light beige":    Color.from_hex("#FFFEB6"),
    "butter yellow":    Color.from_hex("#FFFD74"),
    "dusky purple":    Color.from_hex("#895B7B"),
    "french blue":    Color.from_hex("#436BAD"),
    "ugly yellow":    Color.from_hex("#D0C101"),
    "greeny yellow":    Color.from_hex("#C6F808"),
    "orangish red":    Color.from_hex("#F43605"),
    "shamrock green":    Color.from_hex("#02C14D"),
    "orangish brown":    Color.from_hex("#B25F03"),
    "tree green":    Color.from_hex("#2A7E19"),
    "deep violet":    Color.from_hex("#490648"),
    "gunmetal":    Color.from_hex("#536267"),
    "blue/purple":    Color.from_hex("#5A06EF"),
    "cherry":    Color.from_hex("#CF0234"),
    "sandy brown":    Color.from_hex("#C4A661"),
    "warm grey":    Color.from_hex("#978A84"),
    "dark indigo":    Color.from_hex("#1F0954"),
    "midnight":    Color.from_hex("#03012D"),
    "bluey green":    Color.from_hex("#2BB179"),
    "grey pink":    Color.from_hex("#C3909B"),
    "soft purple":    Color.from_hex("#A66FB5"),
    "blood":    Color.from_hex("#770001"),
    "brown red":    Color.from_hex("#922B05"),
    "medium grey":    Color.from_hex("#7D7F7C"),
    "berry":    Color.from_hex("#990F4B"),
    "poo":    Color.from_hex("#8F7303"),
    "purpley pink":    Color.from_hex("#C83CB9"),
    "light salmon":    Color.from_hex("#FEA993"),
    "snot":    Color.from_hex("#ACBB0D"),
    "easter purple":    Color.from_hex("#C071FE"),
    "light yellow green":    Color.from_hex("#CCFD7F"),
    "dark navy blue":    Color.from_hex("#00022E"),
    "drab":    Color.from_hex("#828344"),
    "light rose":    Color.from_hex("#FFC5CB"),
    "rouge":    Color.from_hex("#AB1239"),
    "purplish red":    Color.from_hex("#B0054B"),
    "slime green":    Color.from_hex("#99CC04"),
    "baby poop":    Color.from_hex("#937C00"),
    "irish green":    Color.from_hex("#019529"),
    "pink/purple":    Color.from_hex("#EF1DE7"),
    "dark navy":    Color.from_hex("#000435"),
    "greeny blue":    Color.from_hex("#42B395"),
    "light plum":    Color.from_hex("#9D5783"),
    "pinkish grey":    Color.from_hex("#C8ACA9"),
    "dirty orange":    Color.from_hex("#C87606"),
    "rust red":    Color.from_hex("#AA2704"),
    "pale lilac":    Color.from_hex("#E4CBFF"),
    "orangey red":    Color.from_hex("#FA4224"),
    "primary blue":    Color.from_hex("#0804F9"),
    "kermit green":    Color.from_hex("#5CB200"),
    "brownish purple":    Color.from_hex("#76424E"),
    "murky green":    Color.from_hex("#6C7A0E"),
    "wheat":    Color.from_hex("#FBDD7E"),
    "very dark purple":    Color.from_hex("#2A0134"),
    "bottle green":    Color.from_hex("#044A05"),
    "watermelon":    Color.from_hex("#FD4659"),
    "deep sky blue":    Color.from_hex("#0D75F8"),
    "fire engine red":    Color.from_hex("#FE0002"),
    "yellow ochre":    Color.from_hex("#CB9D06"),
    "pumpkin orange":    Color.from_hex("#FB7D07"),
    "pale olive":    Color.from_hex("#B9CC81"),
    "light lilac":    Color.from_hex("#EDC8FF"),
    "lightish green":    Color.from_hex("#61E160"),
    "carolina blue":    Color.from_hex("#8AB8FE"),
    "mulberry":    Color.from_hex("#920A4E"),
    "shocking pink":    Color.from_hex("#FE02A2"),
    "auburn":    Color.from_hex("#9A3001"),
    "bright lime green":    Color.from_hex("#65FE08"),
    "celadon":    Color.from_hex("#BEFDB7"),
    "pinkish brown":    Color.from_hex("#B17261"),
    "poo brown":    Color.from_hex("#885F01"),
    "bright sky blue":    Color.from_hex("#02CCFE"),
    "celery":    Color.from_hex("#C1FD95"),
    "dirt brown":    Color.from_hex("#836539"),
    "strawberry":    Color.from_hex("#FB2943"),
    "dark lime":    Color.from_hex("#84B701"),
    "copper":    Color.from_hex("#B66325"),
    "medium brown":    Color.from_hex("#7F5112"),
    "muted green":    Color.from_hex("#5FA052"),
    "robin's egg":    Color.from_hex("#6DEDFD"),
    "bright aqua":    Color.from_hex("#0BF9EA"),
    "bright lavender":    Color.from_hex("#C760FF"),
    "ivory":    Color.from_hex("#FFFFCB"),
    "very light purple":    Color.from_hex("#F6CEFC"),
    "light navy":    Color.from_hex("#155084"),
    "pink red":    Color.from_hex("#F5054F"),
    "olive brown":    Color.from_hex("#645403"),
    "poop brown":    Color.from_hex("#7A5901"),
    "mustard green":    Color.from_hex("#A8B504"),
    "ocean green":    Color.from_hex("#3D9973"),
    "very dark blue":    Color.from_hex("#000133"),
    "dusty green":    Color.from_hex("#76A973"),
    "light navy blue":    Color.from_hex("#2E5A88"),
    "minty green":    Color.from_hex("#0BF77D"),
    "adobe":    Color.from_hex("#BD6C48"),
    "barney":    Color.from_hex("#AC1DB8"),
    "jade green":    Color.from_hex("#2BAF6A"),
    "bright light blue":    Color.from_hex("#26F7FD"),
    "light lime":    Color.from_hex("#AEFD6C"),
    "dark khaki":    Color.from_hex("#9B8F55"),
    "orange yellow":    Color.from_hex("#FFAD01"),
    "ocre":    Color.from_hex("#C69C04"),
    "maize":    Color.from_hex("#F4D054"),
    "faded pink":    Color.from_hex("#DE9DAC"),
    "british racing green":    Color.from_hex("#05480D"),
    "sandstone":    Color.from_hex("#C9AE74"),
    "mud brown":    Color.from_hex("#60460F"),
    "light sea green":    Color.from_hex("#98F6B0"),
    "robin egg blue":    Color.from_hex("#8AF1FE"),
    "aqua marine":    Color.from_hex("#2EE8BB"),
    "dark sea green":    Color.from_hex("#11875D"),
    "soft pink":    Color.from_hex("#FDB0C0"),
    "orangey brown":    Color.from_hex("#B16002"),
    "cherry red":    Color.from_hex("#F7022A"),
    "burnt yellow":    Color.from_hex("#D5AB09"),
    "brownish grey":    Color.from_hex("#86775F"),
    "camel":    Color.from_hex("#C69F59"),
    "purplish grey":    Color.from_hex("#7A687F"),
    "marine":    Color.from_hex("#042E60"),
    "greyish pink":    Color.from_hex("#C88D94"),
    "pale turquoise":    Color.from_hex("#A5FBD5"),
    "pastel yellow":    Color.from_hex("#FFFE71"),
    "bluey purple":    Color.from_hex("#6241C7"),
    "canary yellow":    Color.from_hex("#FFFE40"),
    "faded red":    Color.from_hex("#D3494E"),
    "sepia":    Color.from_hex("#985E2B"),
    "coffee":    Color.from_hex("#A6814C"),
    "bright magenta":    Color.from_hex("#FF08E8"),
    "mocha":    Color.from_hex("#9D7651"),
    "ecru":    Color.from_hex("#FEFFCA"),
    "purpleish":    Color.from_hex("#98568D"),
    "cranberry":    Color.from_hex("#9E003A"),
    "darkish green":    Color.from_hex("#287C37"),
    "brown orange":    Color.from_hex("#B96902"),
    "dusky rose":    Color.from_hex("#BA6873"),
    "melon":    Color.from_hex("#FF7855"),
    "sickly green":    Color.from_hex("#94B21C"),
    "silver":    Color.from_hex("#C5C9C7"),
    "purply blue":    Color.from_hex("#661AEE"),
    "purpleish blue":    Color.from_hex("#6140EF"),
    "hospital green":    Color.from_hex("#9BE5AA"),
    "shit brown":    Color.from_hex("#7B5804"),
    "mid blue":    Color.from_hex("#276AB3"),
    "amber":    Color.from_hex("#FEB308"),
    "easter green":    Color.from_hex("#8CFD7E"),
    "soft blue":    Color.from_hex("#6488EA"),
    "cerulean blue":    Color.from_hex("#056EEE"),
    "golden brown":    Color.from_hex("#B27A01"),
    "bright turquoise":    Color.from_hex("#0FFEF9"),
    "red pink":    Color.from_hex("#FA2A55"),
    "red purple":    Color.from_hex("#820747"),
    "greyish brown":    Color.from_hex("#7A6A4F"),
    "vermillion":    Color.from_hex("#F4320C"),
    "russet":    Color.from_hex("#A13905"),
    "steel grey":    Color.from_hex("#6F828A"),
    "lighter purple":    Color.from_hex("#A55AF4"),
    "bright violet":    Color.from_hex("#AD0AFD"),
    "prussian blue":    Color.from_hex("#004577"),
    "slate green":    Color.from_hex("#658D6D"),
    "dirty pink":    Color.from_hex("#CA7B80"),
    "dark blue green":    Color.from_hex("#005249"),
    "pine":    Color.from_hex("#2B5D34"),
    "yellowy green":    Color.from_hex("#BFF128"),
    "dark gold":    Color.from_hex("#B59410"),
    "bluish":    Color.from_hex("#2976BB"),
    "darkish blue":    Color.from_hex("#014182"),
    "dull red":    Color.from_hex("#BB3F3F"),
    "pinky red":    Color.from_hex("#FC2647"),
    "bronze":    Color.from_hex("#A87900"),
    "pale teal":    Color.from_hex("#82CBB2"),
    "military green":    Color.from_hex("#667C3E"),
    "barbie pink":    Color.from_hex("#FE46A5"),
    "bubblegum pink":    Color.from_hex("#FE83CC"),
    "pea soup green":    Color.from_hex("#94A617"),
    "dark mustard":    Color.from_hex("#A88905"),
    "shit":    Color.from_hex("#7F5F00"),
    "medium purple":    Color.from_hex("#9E43A2"),
    "very dark green":    Color.from_hex("#062E03"),
    "dirt":    Color.from_hex("#8A6E45"),
    "dusky pink":    Color.from_hex("#CC7A8B"),
    "red violet":    Color.from_hex("#9E0168"),
    "lemon yellow":    Color.from_hex("#FDFF38"),
    "pistachio":    Color.from_hex("#C0FA8B"),
    "dull yellow":    Color.from_hex("#EEDC5B"),
    "dark lime green":    Color.from_hex("#7EBD01"),
    "denim blue":    Color.from_hex("#3B5B92"),
    "teal blue":    Color.from_hex("#01889F"),
    "lightish blue":    Color.from_hex("#3D7AFD"),
    "purpley blue":    Color.from_hex("#5F34E7"),
    "light indigo":    Color.from_hex("#6D5ACF"),
    "swamp green":    Color.from_hex("#748500"),
    "brown green":    Color.from_hex("#706C11"),
    "dark maroon":    Color.from_hex("#3C0008"),
    "hot purple":    Color.from_hex("#CB00F5"),
    "dark forest green":    Color.from_hex("#002D04"),
    "faded blue":    Color.from_hex("#658CBB"),
    "drab green":    Color.from_hex("#749551"),
    "light lime green":    Color.from_hex("#B9FF66"),
    "snot green":    Color.from_hex("#9DC100"),
    "yellowish":    Color.from_hex("#FAEE66"),
    "light blue green":    Color.from_hex("#7EFBB3"),
    "bordeaux":    Color.from_hex("#7B002C"),
    "light mauve":    Color.from_hex("#C292A1"),
    "ocean":    Color.from_hex("#017B92"),
    "marigold":    Color.from_hex("#FCC006"),
    "muddy green":    Color.from_hex("#657432"),
    "dull orange":    Color.from_hex("#D8863B"),
    "steel":    Color.from_hex("#738595"),
    "electric purple":    Color.from_hex("#AA23FF"),
    "fluorescent green":    Color.from_hex("#08FF08"),
    "yellowish brown":    Color.from_hex("#9B7A01"),
    "blush":    Color.from_hex("#F29E8E"),
    "soft green":    Color.from_hex("#6FC276"),
    "bright orange":    Color.from_hex("#FF5B00"),
    "lemon":    Color.from_hex("#FDFF52"),
    "purple grey":    Color.from_hex("#866F85"),
    "acid green":    Color.from_hex("#8FFE09"),
    "pale lavender":    Color.from_hex("#EECFFE"),
    "violet blue":    Color.from_hex("#510AC9"),
    "light forest green":    Color.from_hex("#4F9153"),
    "burnt red":    Color.from_hex("#9F2305"),
    "khaki green":    Color.from_hex("#728639"),
    "cerise":    Color.from_hex("#DE0C62"),
    "faded purple":    Color.from_hex("#916E99"),
    "apricot":    Color.from_hex("#FFB16D"),
    "dark olive green":    Color.from_hex("#3C4D03"),
    "grey brown":    Color.from_hex("#7F7053"),
    "green grey":    Color.from_hex("#77926F"),
    "true blue":    Color.from_hex("#010FCC"),
    "pale violet":    Color.from_hex("#CEAEFA"),
    "periwinkle blue":    Color.from_hex("#8F99FB"),
    "light sky blue":    Color.from_hex("#C6FCFF"),
    "blurple":    Color.from_hex("#5539CC"),
    "green brown":    Color.from_hex("#544E03"),
    "bluegreen":    Color.from_hex("#017A79"),
    "bright teal":    Color.from_hex("#01F9C6"),
    "brownish yellow":    Color.from_hex("#C9B003"),
    "pea soup":    Color.from_hex("#929901"),
    "forest":    Color.from_hex("#0B5509"),
    "barney purple":    Color.from_hex("#A00498"),
    "ultramarine":    Color.from_hex("#2000B1"),
    "purplish":    Color.from_hex("#94568C"),
    "puke yellow":    Color.from_hex("#C2BE0E"),
    "bluish grey":    Color.from_hex("#748B97"),
    "dark periwinkle":    Color.from_hex("#665FD1"),
    "dark lilac":    Color.from_hex("#9C6DA5"),
    "reddish":    Color.from_hex("#C44240"),
    "light maroon":    Color.from_hex("#A24857"),
    "dusty purple":    Color.from_hex("#825F87"),
    "terra cotta":    Color.from_hex("#C9643B"),
    "avocado":    Color.from_hex("#90B134"),
    "marine blue":    Color.from_hex("#01386A"),
    "teal green":    Color.from_hex("#25A36F"),
    "slate grey":    Color.from_hex("#59656D"),
    "lighter green":    Color.from_hex("#75FD63"),
    "electric green":    Color.from_hex("#21FC0D"),
    "dusty blue":    Color.from_hex("#5A86AD"),
    "golden yellow":    Color.from_hex("#FEC615"),
    "bright yellow":    Color.from_hex("#FFFD01"),
    "light lavender":    Color.from_hex("#DFC5FE"),
    "umber":    Color.from_hex("#B26400"),
    "poop":    Color.from_hex("#7F5E00"),
    "dark peach":    Color.from_hex("#DE7E5D"),
    "jungle green":    Color.from_hex("#048243"),
    "eggshell":    Color.from_hex("#FFFFD4"),
    "denim":    Color.from_hex("#3B638C"),
    "yellow brown":    Color.from_hex("#B79400"),
    "dull purple":    Color.from_hex("#84597E"),
    "chocolate brown":    Color.from_hex("#411900"),
    "wine red":    Color.from_hex("#7B0323"),
    "neon blue":    Color.from_hex("#04D9FF"),
    "dirty green":    Color.from_hex("#667E2C"),
    "light tan":    Color.from_hex("#FBEEAC"),
    "ice blue":    Color.from_hex("#D7FFFE"),
    "cadet blue":    Color.from_hex("#4E7496"),
    "dark mauve":    Color.from_hex("#874C62"),
    "very light blue":    Color.from_hex("#D5FFFF"),
    "grey purple":    Color.from_hex("#826D8C"),
    "pastel pink":    Color.from_hex("#FFBACD"),
    "very light green":    Color.from_hex("#D1FFBD"),
    "dark sky blue":    Color.from_hex("#448EE4"),
    "evergreen":    Color.from_hex("#05472A"),
    "dull pink":    Color.from_hex("#D5869D"),
    "aubergine":    Color.from_hex("#3D0734"),
    "mahogany":    Color.from_hex("#4A0100"),
    "reddish orange":    Color.from_hex("#F8481C"),
    "deep green":    Color.from_hex("#02590F"),
    "vomit green":    Color.from_hex("#89A203"),
    "purple pink":    Color.from_hex("#E03FD8"),
    "dusty pink":    Color.from_hex("#D58A94"),
    "faded green":    Color.from_hex("#7BB274"),
    "camo green":    Color.from_hex("#526525"),
    "pinky purple":    Color.from_hex("#C94CBE"),
    "pink purple":    Color.from_hex("#DB4BDA"),
    "brownish red":    Color.from_hex("#9E3623"),
    "dark rose":    Color.from_hex("#B5485D"),
    "mud":    Color.from_hex("#735C12"),
    "brownish":    Color.from_hex("#9C6D57"),
    "emerald green":    Color.from_hex("#028F1E"),
    "pale brown":    Color.from_hex("#B1916E"),
    "dull blue":    Color.from_hex("#49759C"),
    "burnt umber":    Color.from_hex("#A0450E"),
    "medium green":    Color.from_hex("#39AD48"),
    "clay":    Color.from_hex("#B66A50"),
    "light aqua":    Color.from_hex("#8CFFDB"),
    "light olive green":    Color.from_hex("#A4BE5C"),
    "brownish orange":    Color.from_hex("#CB7723"),
    "dark aqua":    Color.from_hex("#05696B"),
    "purplish pink":    Color.from_hex("#CE5DAE"),
    "dark salmon":    Color.from_hex("#C85A53"),
    "greenish grey":    Color.from_hex("#96AE8D"),
    "jade":    Color.from_hex("#1FA774"),
    "ugly green":    Color.from_hex("#7A9703"),
    "dark beige":    Color.from_hex("#AC9362"),
    "emerald":    Color.from_hex("#01A049"),
    "pale red":    Color.from_hex("#D9544D"),
    "light magenta":    Color.from_hex("#FA5FF7"),
    "sky":    Color.from_hex("#82CAFC"),
    "light cyan":    Color.from_hex("#ACFFFC"),
    "yellow orange":    Color.from_hex("#FCB001"),
    "reddish purple":    Color.from_hex("#910951"),
    "reddish pink":    Color.from_hex("#FE2C54"),
    "orchid":    Color.from_hex("#C875C4"),
    "dirty yellow":    Color.from_hex("#CDC50A"),
    "orange red":    Color.from_hex("#FD411E"),
    "deep red":    Color.from_hex("#9A0200"),
    "orange brown":    Color.from_hex("#BE6400"),
    "cobalt blue":    Color.from_hex("#030AA7"),
    "neon pink":    Color.from_hex("#FE019A"),
    "rose pink":    Color.from_hex("#F7879A"),
    "greyish purple":    Color.from_hex("#887191"),
    "raspberry":    Color.from_hex("#B00149"),
    "aqua green":    Color.from_hex("#12E193"),
    "salmon pink":    Color.from_hex("#FE7B7C"),
    "tangerine":    Color.from_hex("#FF9408"),
    "brownish green":    Color.from_hex("#6A6E09"),
    "red brown":    Color.from_hex("#8B2E16"),
    "greenish brown":    Color.from_hex("#696112"),
    "pumpkin":    Color.from_hex("#E17701"),
    "pine green":    Color.from_hex("#0A481E"),
    "charcoal":    Color.from_hex("#343837"),
    "baby pink":    Color.from_hex("#FFB7CE"),
    "cornflower":    Color.from_hex("#6A79F7"),
    "blue violet":    Color.from_hex("#5D06E9"),
    "chocolate":    Color.from_hex("#3D1C02"),
    "greyish green":    Color.from_hex("#82A67D"),
    "scarlet":    Color.from_hex("#BE0119"),
    "green yellow":    Color.from_hex("#C9FF27"),
    "dark olive":    Color.from_hex("#373E02"),
    "sienna":    Color.from_hex("#A9561E"),
    "pastel purple":    Color.from_hex("#CAA0FF"),
    "terracotta":    Color.from_hex("#CA6641"),
    "aqua blue":    Color.from_hex("#02D8E9"),
    "sage green":    Color.from_hex("#88B378"),
    "blood red":    Color.from_hex("#980002"),
    "deep pink":    Color.from_hex("#CB0162"),
    "grass":    Color.from_hex("#5CAC2D"),
    "moss":    Color.from_hex("#769958"),
    "pastel blue":    Color.from_hex("#A2BFFE"),
    "bluish green":    Color.from_hex("#10A674"),
    "green blue":    Color.from_hex("#06B48B"),
    "dark tan":    Color.from_hex("#AF884A"),
    "greenish blue":    Color.from_hex("#0B8B87"),
    "pale orange":    Color.from_hex("#FFA756"),
    "vomit":    Color.from_hex("#A2A415"),
    "forrest green":    Color.from_hex("#154406"),
    "dark lavender":    Color.from_hex("#856798"),
    "dark violet":    Color.from_hex("#34013F"),
    "purple blue":    Color.from_hex("#632DE9"),
    "dark cyan":    Color.from_hex("#0A888A"),
    "olive drab":    Color.from_hex("#6F7632"),
    "pinkish":    Color.from_hex("#D46A7E"),
    "cobalt":    Color.from_hex("#1E488F"),
    "neon purple":    Color.from_hex("#BC13FE"),
    "light turquoise":    Color.from_hex("#7EF4CC"),
    "apple green":    Color.from_hex("#76CD26"),
    "dull green":    Color.from_hex("#74A662"),
    "wine":    Color.from_hex("#80013F"),
    "powder blue":    Color.from_hex("#B1D1FC"),
    "off white":    Color.from_hex("#FFFFE4"),
    "electric blue":    Color.from_hex("#0652FF"),
    "dark turquoise":    Color.from_hex("#045C5A"),
    "blue purple":    Color.from_hex("#5729CE"),
    "azure":    Color.from_hex("#069AF3"),
    "bright red":    Color.from_hex("#FF000D"),
    "pinkish red":    Color.from_hex("#F10C45"),
    "cornflower blue":    Color.from_hex("#5170D7"),
    "light olive":    Color.from_hex("#ACBF69"),
    "grape":    Color.from_hex("#6C3461"),
    "greyish blue":    Color.from_hex("#5E819D"),
    "purplish blue":    Color.from_hex("#601EF9"),
    "yellowish green":    Color.from_hex("#B0DD16"),
    "greenish yellow":    Color.from_hex("#CDFD02"),
    "medium blue":    Color.from_hex("#2C6FBB"),
    "dusty rose":    Color.from_hex("#C0737A"),
    "light violet":    Color.from_hex("#D6B4FC"),
    "midnight blue":    Color.from_hex("#020035"),
    "bluish purple":    Color.from_hex("#703BE7"),
    "red orange":    Color.from_hex("#FD3C06"),
    "dark magenta":    Color.from_hex("#960056"),
    "greenish":    Color.from_hex("#40A368"),
    "ocean blue":    Color.from_hex("#03719C"),
    "coral":    Color.from_hex("#FC5A50"),
    "cream":    Color.from_hex("#FFFFC2"),
    "reddish brown":    Color.from_hex("#7F2B0A"),
    "burnt sienna":    Color.from_hex("#B04E0F"),
    "brick":    Color.from_hex("#A03623"),
    "sage":    Color.from_hex("#87AE73"),
    "grey green":    Color.from_hex("#789B73"),
    "white":    Color.from_hex("#FFFFFF"),
    "robin's egg blue":    Color.from_hex("#98EFF9"),
    "moss green":    Color.from_hex("#658B38"),
    "steel blue":    Color.from_hex("#5A7D9A"),
    "eggplant":    Color.from_hex("#380835"),
    "light yellow":    Color.from_hex("#FFFE7A"),
    "leaf green":    Color.from_hex("#5CA904"),
    "light grey":    Color.from_hex("#D8DCD6"),
    "puke":    Color.from_hex("#A5A502"),
    "pinkish purple":    Color.from_hex("#D648D7"),
    "sea blue":    Color.from_hex("#047495"),
    "pale purple":    Color.from_hex("#B790D4"),
    "slate blue":    Color.from_hex("#5B7C99"),
    "blue grey":    Color.from_hex("#607C8E"),
    "hunter green":    Color.from_hex("#0B4008"),
    "fuchsia":    Color.from_hex("#ED0DD9"),
    "crimson":    Color.from_hex("#8C000F"),
    "pale yellow":    Color.from_hex("#FFFF84"),
    "ochre":    Color.from_hex("#BF9005"),
    "mustard yellow":    Color.from_hex("#D2BD0A"),
    "light red":    Color.from_hex("#FF474C"),
    "cerulean":    Color.from_hex("#0485D1"),
    "pale pink":    Color.from_hex("#FFCFDC"),
    "deep blue":    Color.from_hex("#040273"),
    "rust":    Color.from_hex("#A83C09"),
    "light teal":    Color.from_hex("#90E4C1"),
    "slate":    Color.from_hex("#516572"),
    "goldenrod":    Color.from_hex("#FAC205"),
    "dark yellow":    Color.from_hex("#D5B60A"),
    "dark grey":    Color.from_hex("#363737"),
    "army green":    Color.from_hex("#4B5D16"),
    "grey blue":    Color.from_hex("#6B8BA4"),
    "seafoam":    Color.from_hex("#80F9AD"),
    "puce":    Color.from_hex("#A57E52"),
    "spring green":    Color.from_hex("#A9F971"),
    "dark orange":    Color.from_hex("#C65102"),
    "sand":    Color.from_hex("#E2CA76"),
    "pastel green":    Color.from_hex("#B0FF9D"),
    "mint":    Color.from_hex("#9FFEB0"),
    "light orange":    Color.from_hex("#FDAA48"),
    "bright pink":    Color.from_hex("#FE01B1"),
    "chartreuse":    Color.from_hex("#C1F80A"),
    "deep purple":    Color.from_hex("#36013F"),
    "dark brown":    Color.from_hex("#341C02"),
    "taupe":    Color.from_hex("#B9A281"),
    "pea green":    Color.from_hex("#8EAB12"),
    "puke green":    Color.from_hex("#9AAE07"),
    "kelly green":    Color.from_hex("#02AB2E"),
    "seafoam green":    Color.from_hex("#7AF9AB"),
    "blue green":    Color.from_hex("#137E6D"),
    "khaki":    Color.from_hex("#AAA662"),
    "burgundy":    Color.from_hex("#610023"),
    "dark teal":    Color.from_hex("#014D4E"),
    "brick red":    Color.from_hex("#8F1402"),
    "royal purple":    Color.from_hex("#4B006E"),
    "plum":    Color.from_hex("#580F41"),
    "mint green":    Color.from_hex("#8FFF9F"),
    "gold":    Color.from_hex("#DBB40C"),
    "baby blue":    Color.from_hex("#A2CFFE"),
    "yellow green":    Color.from_hex("#C0FB2D"),
    "bright purple":    Color.from_hex("#BE03FD"),
    "dark red":    Color.from_hex("#840000"),
    "pale blue":    Color.from_hex("#D0FEFE"),
    "grass green":    Color.from_hex("#3F9B0B"),
    "navy":    Color.from_hex("#01153E"),
    "aquamarine":    Color.from_hex("#04D8B2"),
    "burnt orange":    Color.from_hex("#C04E01"),
    "neon green":    Color.from_hex("#0CFF0C"),
    "bright blue":    Color.from_hex("#0165FC"),
    "rose":    Color.from_hex("#CF6275"),
    "light pink":    Color.from_hex("#FFD1DF"),
    "mustard":    Color.from_hex("#CEB301"),
    "indigo":    Color.from_hex("#380282"),
    "lime":    Color.from_hex("#AAFF32"),
    "sea green":    Color.from_hex("#53FCA1"),
    "periwinkle":    Color.from_hex("#8E82FE"),
    "dark pink":    Color.from_hex("#CB416B"),
    "olive green":    Color.from_hex("#677A04"),
    "peach":    Color.from_hex("#FFB07C"),
    "pale green":    Color.from_hex("#C7FDB5"),
    "light brown":    Color.from_hex("#AD8150"),
    "hot pink":    Color.from_hex("#FF028D"),
    "black":    Color.from_hex("#000000"),
    "lilac":    Color.from_hex("#CEA2FD"),
    "navy blue":    Color.from_hex("#001146"),
    "royal blue":    Color.from_hex("#0504AA"),
    "beige":    Color.from_hex("#E6DAA6"),
    "salmon":    Color.from_hex("#FF796C"),
    "olive":    Color.from_hex("#6E750E"),
    "maroon":    Color.from_hex("#650021"),
    "bright green":    Color.from_hex("#01FF07"),
    "dark purple":    Color.from_hex("#35063E"),
    "mauve":    Color.from_hex("#AE7181"),
    "forest green":    Color.from_hex("#06470C"),
    "aqua":    Color.from_hex("#13EAC9"),
    "cyan":    Color.from_hex("#00FFFF"),
    "tan":    Color.from_hex("#D1B26F"),
    "dark blue":    Color.from_hex("#00035B"),
    "lavender":    Color.from_hex("#C79FEF"),
    "turquoise":    Color.from_hex("#06C2AC"),
    "dark green":    Color.from_hex("#033500"),
    "violet":    Color.from_hex("#9A0EEA"),
    "light purple":    Color.from_hex("#BF77F6"),
    "lime green":    Color.from_hex("#89FE05"),
    "grey":    Color.from_hex("#929591"),
    "sky blue":    Color.from_hex("#75BBFD"),
    "yellow":    Color.from_hex("#FFFF14"),
    "magenta":    Color.from_hex("#C20078"),
    "light green":    Color.from_hex("#96F97B"),
    "orange":    Color.from_hex("#F97306"),
    "teal":    Color.from_hex("#029386"),
    "light blue":    Color.from_hex("#95D0FC"),
    "red":    Color.from_hex("#E50000"),
    "brown":    Color.from_hex("#653700"),
    "pink":    Color.from_hex("#FF81C0"),
    "blue":    Color.from_hex("#0343DF"),
    "green":    Color.from_hex("#15B01A"),
    "purple":    Color.from_hex("#7E1E9C")
}


# selection of 48 colors from xkcd palette + white
# (those are colors published directly on mentioned article)
XKCD_49_PALETTE = {
    "light pink":    Color.from_hex("#FFD1DF"),
    "mustard":    Color.from_hex("#CEB301"),
    "indigo":    Color.from_hex("#380282"),
    "lime":    Color.from_hex("#AAFF32"),
    "sea green":    Color.from_hex("#53FCA1"),
    "periwinkle":    Color.from_hex("#8E82FE"),
    "dark pink":    Color.from_hex("#CB416B"),
    "olive green":    Color.from_hex("#677A04"),
    "peach":    Color.from_hex("#FFB07C"),
    "pale green":    Color.from_hex("#C7FDB5"),
    "light brown":    Color.from_hex("#AD8150"),
    "hot pink":    Color.from_hex("#FF028D"),
    "black":    Color.from_hex("#000000"),
    "lilac":    Color.from_hex("#CEA2FD"),
    "navy blue":    Color.from_hex("#001146"),
    "royal blue":    Color.from_hex("#0504AA"),
    "beige":    Color.from_hex("#E6DAA6"),
    "salmon":    Color.from_hex("#FF796C"),
    "olive":    Color.from_hex("#6E750E"),
    "maroon":    Color.from_hex("#650021"),
    "bright green":    Color.from_hex("#01FF07"),
    "dark purple":    Color.from_hex("#35063E"),
    "mauve":    Color.from_hex("#AE7181"),
    "forest green":    Color.from_hex("#06470C"),
    "aqua":    Color.from_hex("#13EAC9"),
    "cyan":    Color.from_hex("#00FFFF"),
    "tan":    Color.from_hex("#D1B26F"),
    "dark blue":    Color.from_hex("#00035B"),
    "lavender":    Color.from_hex("#C79FEF"),
    "turquoise":    Color.from_hex("#06C2AC"),
    "dark green":    Color.from_hex("#033500"),
    "violet":    Color.from_hex("#9A0EEA"),
    "light purple":    Color.from_hex("#BF77F6"),
    "lime green":    Color.from_hex("#89FE05"),
    "grey":    Color.from_hex("#929591"),
    "sky blue":    Color.from_hex("#75BBFD"),
    "yellow":    Color.from_hex("#FFFF14"),
    "magenta":    Color.from_hex("#C20078"),
    "light green":    Color.from_hex("#96F97B"),
    "orange":    Color.from_hex("#F97306"),
    "teal":    Color.from_hex("#029386"),
    "light blue":    Color.from_hex("#95D0FC"),
    "red":    Color.from_hex("#E50000"),
    "brown":    Color.from_hex("#653700"),
    "pink":    Color.from_hex("#FF81C0"),
    "blue":    Color.from_hex("#0343DF"),
    "green":    Color.from_hex("#15B01A"),
    "purple":    Color.from_hex("#7E1E9C"),
    "white":    Color.from_hex("#FFFFFF")
}

# all available palettes
PALETTES = {
    "web": WEB_PALETTE,
    "xkcd_full": XKCD_FULL_PALETTE,
    "xkcd_49": XKCD_49_PALETTE
}


class PaletteColorsCounter(dict):
    """ Helper class for counting occurrences of a given color. """

    @staticmethod
    def from_palette(palette):
        """ Constructs dict with pre-populated keys from a given palette dict.

         Sets initial counters to 0 for each key.
        """
        return PaletteColorsCounter(**{k:0 for k in palette.keys()})