# encoding: utf-8
from colors_classifier.colors import Color


# pallete of 16 commonly used web colors
# in accordance to HTML 4.01
# (http://en.wikipedia.org/wiki/Web_colors)
WEB_PALETTE = {
    "white":    Color.from_hex("#FFFFFF").rgb,
    "silver":   Color.from_hex("#C0C0C0").rgb,
    "gray":     Color.from_hex("#808080").rgb,
    "black":    Color.from_hex("#000000").rgb,
    "red":      Color.from_hex("#FF0000").rgb,
    "maroon":   Color.from_hex("#800000").rgb,
    "yellow":   Color.from_hex("#FFFF00").rgb,
    "olive":    Color.from_hex("#808000").rgb,
    "lime":     Color.from_hex("#00FF00").rgb,
    "green":    Color.from_hex("#008000").rgb,
    "aqua":     Color.from_hex("#00FFFF").rgb,
    "teal":     Color.from_hex("#008080").rgb,
    "blue":     Color.from_hex("#0000FF").rgb,
    "navy":     Color.from_hex("#000080").rgb,
    "fuchsia":  Color.from_hex("#FF00FF").rgb,
    "purple":   Color.from_hex("#800080").rgb
}


# palette created as a result of survey
# published by xkcd: http://blog.xkcd.com/2010/05/03/color-survey-results/
XKCD_FULL_PALETTE = {
    "cloudy blue":    Color.from_hex("#ACC2D9").rgb,
    "dark pastel green":    Color.from_hex("#56AE57").rgb,
    "dust":    Color.from_hex("#B2996E").rgb,
    "electric lime":    Color.from_hex("#A8FF04").rgb,
    "fresh green":    Color.from_hex("#69D84F").rgb,
    "light eggplant":    Color.from_hex("#894585").rgb,
    "nasty green":    Color.from_hex("#70B23F").rgb,
    "really light blue":    Color.from_hex("#D4FFFF").rgb,
    "tea":    Color.from_hex("#65AB7C").rgb,
    "warm purple":    Color.from_hex("#952E8F").rgb,
    "yellowish tan":    Color.from_hex("#FCFC81").rgb,
    "cement":    Color.from_hex("#A5A391").rgb,
    "dark grass green":    Color.from_hex("#388004").rgb,
    "dusty teal":    Color.from_hex("#4C9085").rgb,
    "grey teal":    Color.from_hex("#5E9B8A").rgb,
    "macaroni and cheese":    Color.from_hex("#EFB435").rgb,
    "pinkish tan":    Color.from_hex("#D99B82").rgb,
    "spruce":    Color.from_hex("#0A5F38").rgb,
    "strong blue":    Color.from_hex("#0C06F7").rgb,
    "toxic green":    Color.from_hex("#61DE2A").rgb,
    "windows blue":    Color.from_hex("#3778BF").rgb,
    "blue blue":    Color.from_hex("#2242C7").rgb,
    "blue with a hint of purple":    Color.from_hex("#533CC6").rgb,
    "booger":    Color.from_hex("#9BB53C").rgb,
    "bright sea green":    Color.from_hex("#05FFA6").rgb,
    "dark green blue":    Color.from_hex("#1F6357").rgb,
    "deep turquoise":    Color.from_hex("#017374").rgb,
    "green teal":    Color.from_hex("#0CB577").rgb,
    "strong pink":    Color.from_hex("#FF0789").rgb,
    "bland":    Color.from_hex("#AFA88B").rgb,
    "deep aqua":    Color.from_hex("#08787F").rgb,
    "lavender pink":    Color.from_hex("#DD85D7").rgb,
    "light moss green":    Color.from_hex("#A6C875").rgb,
    "light seafoam green":    Color.from_hex("#A7FFB5").rgb,
    "olive yellow":    Color.from_hex("#C2B709").rgb,
    "pig pink":    Color.from_hex("#E78EA5").rgb,
    "deep lilac":    Color.from_hex("#966EBD").rgb,
    "desert":    Color.from_hex("#CCAD60").rgb,
    "dusty lavender":    Color.from_hex("#AC86A8").rgb,
    "purpley grey":    Color.from_hex("#947E94").rgb,
    "purply":    Color.from_hex("#983FB2").rgb,
    "candy pink":    Color.from_hex("#FF63E9").rgb,
    "light pastel green":    Color.from_hex("#B2FBA5").rgb,
    "boring green":    Color.from_hex("#63B365").rgb,
    "kiwi green":    Color.from_hex("#8EE53F").rgb,
    "light grey green":    Color.from_hex("#B7E1A1").rgb,
    "orange pink":    Color.from_hex("#FF6F52").rgb,
    "tea green":    Color.from_hex("#BDF8A3").rgb,
    "very light brown":    Color.from_hex("#D3B683").rgb,
    "egg shell":    Color.from_hex("#FFFCC4").rgb,
    "eggplant purple":    Color.from_hex("#430541").rgb,
    "powder pink":    Color.from_hex("#FFB2D0").rgb,
    "reddish grey":    Color.from_hex("#997570").rgb,
    "baby shit brown":    Color.from_hex("#AD900D").rgb,
    "liliac":    Color.from_hex("#C48EFD").rgb,
    "stormy blue":    Color.from_hex("#507B9C").rgb,
    "ugly brown":    Color.from_hex("#7D7103").rgb,
    "custard":    Color.from_hex("#FFFD78").rgb,
    "darkish pink":    Color.from_hex("#DA467D").rgb,
    "deep brown":    Color.from_hex("#410200").rgb,
    "greenish beige":    Color.from_hex("#C9D179").rgb,
    "manilla":    Color.from_hex("#FFFA86").rgb,
    "off blue":    Color.from_hex("#5684AE").rgb,
    "battleship grey":    Color.from_hex("#6B7C85").rgb,
    "browny green":    Color.from_hex("#6F6C0A").rgb,
    "bruise":    Color.from_hex("#7E4071").rgb,
    "kelley green":    Color.from_hex("#009337").rgb,
    "sickly yellow":    Color.from_hex("#D0E429").rgb,
    "sunny yellow":    Color.from_hex("#FFF917").rgb,
    "azul":    Color.from_hex("#1D5DEC").rgb,
    "darkgreen":    Color.from_hex("#054907").rgb,
    "green/yellow":    Color.from_hex("#B5CE08").rgb,
    "lichen":    Color.from_hex("#8FB67B").rgb,
    "light light green":    Color.from_hex("#C8FFB0").rgb,
    "pale gold":    Color.from_hex("#FDDE6C").rgb,
    "sun yellow":    Color.from_hex("#FFDF22").rgb,
    "tan green":    Color.from_hex("#A9BE70").rgb,
    "burple":    Color.from_hex("#6832E3").rgb,
    "butterscotch":    Color.from_hex("#FDB147").rgb,
    "toupe":    Color.from_hex("#C7AC7D").rgb,
    "dark cream":    Color.from_hex("#FFF39A").rgb,
    "indian red":    Color.from_hex("#850E04").rgb,
    "light lavendar":    Color.from_hex("#EFC0FE").rgb,
    "poison green":    Color.from_hex("#40FD14").rgb,
    "baby puke green":    Color.from_hex("#B6C406").rgb,
    "bright yellow green":    Color.from_hex("#9DFF00").rgb,
    "charcoal grey":    Color.from_hex("#3C4142").rgb,
    "squash":    Color.from_hex("#F2AB15").rgb,
    "cinnamon":    Color.from_hex("#AC4F06").rgb,
    "light pea green":    Color.from_hex("#C4FE82").rgb,
    "radioactive green":    Color.from_hex("#2CFA1F").rgb,
    "raw sienna":    Color.from_hex("#9A6200").rgb,
    "baby purple":    Color.from_hex("#CA9BF7").rgb,
    "cocoa":    Color.from_hex("#875F42").rgb,
    "light royal blue":    Color.from_hex("#3A2EFE").rgb,
    "orangeish":    Color.from_hex("#FD8D49").rgb,
    "rust brown":    Color.from_hex("#8B3103").rgb,
    "sand brown":    Color.from_hex("#CBA560").rgb,
    "swamp":    Color.from_hex("#698339").rgb,
    "tealish green":    Color.from_hex("#0CDC73").rgb,
    "burnt siena":    Color.from_hex("#B75203").rgb,
    "camo":    Color.from_hex("#7F8F4E").rgb,
    "dusk blue":    Color.from_hex("#26538D").rgb,
    "fern":    Color.from_hex("#63A950").rgb,
    "old rose":    Color.from_hex("#C87F89").rgb,
    "pale light green":    Color.from_hex("#B1FC99").rgb,
    "peachy pink":    Color.from_hex("#FF9A8A").rgb,
    "rosy pink":    Color.from_hex("#F6688E").rgb,
    "light bluish green":    Color.from_hex("#76FDA8").rgb,
    "light bright green":    Color.from_hex("#53FE5C").rgb,
    "light neon green":    Color.from_hex("#4EFD54").rgb,
    "light seafoam":    Color.from_hex("#A0FEBF").rgb,
    "tiffany blue":    Color.from_hex("#7BF2DA").rgb,
    "washed out green":    Color.from_hex("#BCF5A6").rgb,
    "browny orange":    Color.from_hex("#CA6B02").rgb,
    "nice blue":    Color.from_hex("#107AB0").rgb,
    "sapphire":    Color.from_hex("#2138AB").rgb,
    "greyish teal":    Color.from_hex("#719F91").rgb,
    "orangey yellow":    Color.from_hex("#FDB915").rgb,
    "parchment":    Color.from_hex("#FEFCAF").rgb,
    "straw":    Color.from_hex("#FCF679").rgb,
    "very dark brown":    Color.from_hex("#1D0200").rgb,
    "terracota":    Color.from_hex("#CB6843").rgb,
    "ugly blue":    Color.from_hex("#31668A").rgb,
    "clear blue":    Color.from_hex("#247AFD").rgb,
    "creme":    Color.from_hex("#FFFFB6").rgb,
    "foam green":    Color.from_hex("#90FDA9").rgb,
    "grey/green":    Color.from_hex("#86A17D").rgb,
    "light gold":    Color.from_hex("#FDDC5C").rgb,
    "seafoam blue":    Color.from_hex("#78D1B6").rgb,
    "topaz":    Color.from_hex("#13BBAF").rgb,
    "violet pink":    Color.from_hex("#FB5FFC").rgb,
    "wintergreen":    Color.from_hex("#20F986").rgb,
    "yellow tan":    Color.from_hex("#FFE36E").rgb,
    "dark fuchsia":    Color.from_hex("#9D0759").rgb,
    "indigo blue":    Color.from_hex("#3A18B1").rgb,
    "light yellowish green":    Color.from_hex("#C2FF89").rgb,
    "pale magenta":    Color.from_hex("#D767AD").rgb,
    "rich purple":    Color.from_hex("#720058").rgb,
    "sunflower yellow":    Color.from_hex("#FFDA03").rgb,
    "green/blue":    Color.from_hex("#01C08D").rgb,
    "leather":    Color.from_hex("#AC7434").rgb,
    "racing green":    Color.from_hex("#014600").rgb,
    "vivid purple":    Color.from_hex("#9900FA").rgb,
    "dark royal blue":    Color.from_hex("#02066F").rgb,
    "hazel":    Color.from_hex("#8E7618").rgb,
    "muted pink":    Color.from_hex("#D1768F").rgb,
    "booger green":    Color.from_hex("#96B403").rgb,
    "canary":    Color.from_hex("#FDFF63").rgb,
    "cool grey":    Color.from_hex("#95A3A6").rgb,
    "dark taupe":    Color.from_hex("#7F684E").rgb,
    "darkish purple":    Color.from_hex("#751973").rgb,
    "true green":    Color.from_hex("#089404").rgb,
    "coral pink":    Color.from_hex("#FF6163").rgb,
    "dark sage":    Color.from_hex("#598556").rgb,
    "dark slate blue":    Color.from_hex("#214761").rgb,
    "flat blue":    Color.from_hex("#3C73A8").rgb,
    "mushroom":    Color.from_hex("#BA9E88").rgb,
    "rich blue":    Color.from_hex("#021BF9").rgb,
    "dirty purple":    Color.from_hex("#734A65").rgb,
    "greenblue":    Color.from_hex("#23C48B").rgb,
    "icky green":    Color.from_hex("#8FAE22").rgb,
    "light khaki":    Color.from_hex("#E6F2A2").rgb,
    "warm blue":    Color.from_hex("#4B57DB").rgb,
    "dark hot pink":    Color.from_hex("#D90166").rgb,
    "deep sea blue":    Color.from_hex("#015482").rgb,
    "carmine":    Color.from_hex("#9D0216").rgb,
    "dark yellow green":    Color.from_hex("#728F02").rgb,
    "pale peach":    Color.from_hex("#FFE5AD").rgb,
    "plum purple":    Color.from_hex("#4E0550").rgb,
    "golden rod":    Color.from_hex("#F9BC08").rgb,
    "neon red":    Color.from_hex("#FF073A").rgb,
    "old pink":    Color.from_hex("#C77986").rgb,
    "very pale blue":    Color.from_hex("#D6FFFE").rgb,
    "blood orange":    Color.from_hex("#FE4B03").rgb,
    "grapefruit":    Color.from_hex("#FD5956").rgb,
    "sand yellow":    Color.from_hex("#FCE166").rgb,
    "clay brown":    Color.from_hex("#B2713D").rgb,
    "dark blue grey":    Color.from_hex("#1F3B4D").rgb,
    "flat green":    Color.from_hex("#699D4C").rgb,
    "light green blue":    Color.from_hex("#56FCA2").rgb,
    "warm pink":    Color.from_hex("#FB5581").rgb,
    "dodger blue":    Color.from_hex("#3E82FC").rgb,
    "gross green":    Color.from_hex("#A0BF16").rgb,
    "ice":    Color.from_hex("#D6FFFA").rgb,
    "metallic blue":    Color.from_hex("#4F738E").rgb,
    "pale salmon":    Color.from_hex("#FFB19A").rgb,
    "sap green":    Color.from_hex("#5C8B15").rgb,
    "algae":    Color.from_hex("#54AC68").rgb,
    "bluey grey":    Color.from_hex("#89A0B0").rgb,
    "greeny grey":    Color.from_hex("#7EA07A").rgb,
    "highlighter green":    Color.from_hex("#1BFC06").rgb,
    "light light blue":    Color.from_hex("#CAFFFB").rgb,
    "light mint":    Color.from_hex("#B6FFBB").rgb,
    "raw umber":    Color.from_hex("#A75E09").rgb,
    "vivid blue":    Color.from_hex("#152EFF").rgb,
    "deep lavender":    Color.from_hex("#8D5EB7").rgb,
    "dull teal":    Color.from_hex("#5F9E8F").rgb,
    "light greenish blue":    Color.from_hex("#63F7B4").rgb,
    "mud green":    Color.from_hex("#606602").rgb,
    "pinky":    Color.from_hex("#FC86AA").rgb,
    "red wine":    Color.from_hex("#8C0034").rgb,
    "shit green":    Color.from_hex("#758000").rgb,
    "tan brown":    Color.from_hex("#AB7E4C").rgb,
    "darkblue":    Color.from_hex("#030764").rgb,
    "rosa":    Color.from_hex("#FE86A4").rgb,
    "lipstick":    Color.from_hex("#D5174E").rgb,
    "pale mauve":    Color.from_hex("#FED0FC").rgb,
    "claret":    Color.from_hex("#680018").rgb,
    "dandelion":    Color.from_hex("#FEDF08").rgb,
    "orangered":    Color.from_hex("#FE420F").rgb,
    "poop green":    Color.from_hex("#6F7C00").rgb,
    "ruby":    Color.from_hex("#CA0147").rgb,
    "dark":    Color.from_hex("#1B2431").rgb,
    "greenish turquoise":    Color.from_hex("#00FBB0").rgb,
    "pastel red":    Color.from_hex("#DB5856").rgb,
    "piss yellow":    Color.from_hex("#DDD618").rgb,
    "bright cyan":    Color.from_hex("#41FDFE").rgb,
    "dark coral":    Color.from_hex("#CF524E").rgb,
    "algae green":    Color.from_hex("#21C36F").rgb,
    "darkish red":    Color.from_hex("#A90308").rgb,
    "reddy brown":    Color.from_hex("#6E1005").rgb,
    "blush pink":    Color.from_hex("#FE828C").rgb,
    "camouflage green":    Color.from_hex("#4B6113").rgb,
    "lawn green":    Color.from_hex("#4DA409").rgb,
    "putty":    Color.from_hex("#BEAE8A").rgb,
    "vibrant blue":    Color.from_hex("#0339F8").rgb,
    "dark sand":    Color.from_hex("#A88F59").rgb,
    "purple/blue":    Color.from_hex("#5D21D0").rgb,
    "saffron":    Color.from_hex("#FEB209").rgb,
    "twilight":    Color.from_hex("#4E518B").rgb,
    "warm brown":    Color.from_hex("#964E02").rgb,
    "bluegrey":    Color.from_hex("#85A3B2").rgb,
    "bubble gum pink":    Color.from_hex("#FF69AF").rgb,
    "duck egg blue":    Color.from_hex("#C3FBF4").rgb,
    "greenish cyan":    Color.from_hex("#2AFEB7").rgb,
    "petrol":    Color.from_hex("#005F6A").rgb,
    "royal":    Color.from_hex("#0C1793").rgb,
    "butter":    Color.from_hex("#FFFF81").rgb,
    "dusty orange":    Color.from_hex("#F0833A").rgb,
    "off yellow":    Color.from_hex("#F1F33F").rgb,
    "pale olive green":    Color.from_hex("#B1D27B").rgb,
    "orangish":    Color.from_hex("#FC824A").rgb,
    "leaf":    Color.from_hex("#71AA34").rgb,
    "light blue grey":    Color.from_hex("#B7C9E2").rgb,
    "dried blood":    Color.from_hex("#4B0101").rgb,
    "lightish purple":    Color.from_hex("#A552E6").rgb,
    "rusty red":    Color.from_hex("#AF2F0D").rgb,
    "lavender blue":    Color.from_hex("#8B88F8").rgb,
    "light grass green":    Color.from_hex("#9AF764").rgb,
    "light mint green":    Color.from_hex("#A6FBB2").rgb,
    "sunflower":    Color.from_hex("#FFC512").rgb,
    "velvet":    Color.from_hex("#750851").rgb,
    "brick orange":    Color.from_hex("#C14A09").rgb,
    "lightish red":    Color.from_hex("#FE2F4A").rgb,
    "pure blue":    Color.from_hex("#0203E2").rgb,
    "twilight blue":    Color.from_hex("#0A437A").rgb,
    "violet red":    Color.from_hex("#A50055").rgb,
    "yellowy brown":    Color.from_hex("#AE8B0C").rgb,
    "carnation":    Color.from_hex("#FD798F").rgb,
    "muddy yellow":    Color.from_hex("#BFAC05").rgb,
    "dark seafoam green":    Color.from_hex("#3EAF76").rgb,
    "deep rose":    Color.from_hex("#C74767").rgb,
    "dusty red":    Color.from_hex("#B9484E").rgb,
    "grey/blue":    Color.from_hex("#647D8E").rgb,
    "lemon lime":    Color.from_hex("#BFFE28").rgb,
    "purple/pink":    Color.from_hex("#D725DE").rgb,
    "brown yellow":    Color.from_hex("#B29705").rgb,
    "purple brown":    Color.from_hex("#673A3F").rgb,
    "wisteria":    Color.from_hex("#A87DC2").rgb,
    "banana yellow":    Color.from_hex("#FAFE4B").rgb,
    "lipstick red":    Color.from_hex("#C0022F").rgb,
    "water blue":    Color.from_hex("#0E87CC").rgb,
    "brown grey":    Color.from_hex("#8D8468").rgb,
    "vibrant purple":    Color.from_hex("#AD03DE").rgb,
    "baby green":    Color.from_hex("#8CFF9E").rgb,
    "barf green":    Color.from_hex("#94AC02").rgb,
    "eggshell blue":    Color.from_hex("#C4FFF7").rgb,
    "sandy yellow":    Color.from_hex("#FDEE73").rgb,
    "cool green":    Color.from_hex("#33B864").rgb,
    "pale":    Color.from_hex("#FFF9D0").rgb,
    "blue/grey":    Color.from_hex("#758DA3").rgb,
    "hot magenta":    Color.from_hex("#F504C9").rgb,
    "greyblue":    Color.from_hex("#77A1B5").rgb,
    "purpley":    Color.from_hex("#8756E4").rgb,
    "baby shit green":    Color.from_hex("#889717").rgb,
    "brownish pink":    Color.from_hex("#C27E79").rgb,
    "dark aquamarine":    Color.from_hex("#017371").rgb,
    "diarrhea":    Color.from_hex("#9F8303").rgb,
    "light mustard":    Color.from_hex("#F7D560").rgb,
    "pale sky blue":    Color.from_hex("#BDF6FE").rgb,
    "turtle green":    Color.from_hex("#75B84F").rgb,
    "bright olive":    Color.from_hex("#9CBB04").rgb,
    "dark grey blue":    Color.from_hex("#29465B").rgb,
    "greeny brown":    Color.from_hex("#696006").rgb,
    "lemon green":    Color.from_hex("#ADF802").rgb,
    "light periwinkle":    Color.from_hex("#C1C6FC").rgb,
    "seaweed green":    Color.from_hex("#35AD6B").rgb,
    "sunshine yellow":    Color.from_hex("#FFFD37").rgb,
    "ugly purple":    Color.from_hex("#A442A0").rgb,
    "medium pink":    Color.from_hex("#F36196").rgb,
    "puke brown":    Color.from_hex("#947706").rgb,
    "very light pink":    Color.from_hex("#FFF4F2").rgb,
    "viridian":    Color.from_hex("#1E9167").rgb,
    "bile":    Color.from_hex("#B5C306").rgb,
    "faded yellow":    Color.from_hex("#FEFF7F").rgb,
    "very pale green":    Color.from_hex("#CFFDBC").rgb,
    "vibrant green":    Color.from_hex("#0ADD08").rgb,
    "bright lime":    Color.from_hex("#87FD05").rgb,
    "spearmint":    Color.from_hex("#1EF876").rgb,
    "light aquamarine":    Color.from_hex("#7BFDC7").rgb,
    "light sage":    Color.from_hex("#BCECAC").rgb,
    "yellowgreen":    Color.from_hex("#BBF90F").rgb,
    "baby poo":    Color.from_hex("#AB9004").rgb,
    "dark seafoam":    Color.from_hex("#1FB57A").rgb,
    "deep teal":    Color.from_hex("#00555A").rgb,
    "heather":    Color.from_hex("#A484AC").rgb,
    "rust orange":    Color.from_hex("#C45508").rgb,
    "dirty blue":    Color.from_hex("#3F829D").rgb,
    "fern green":    Color.from_hex("#548D44").rgb,
    "bright lilac":    Color.from_hex("#C95EFB").rgb,
    "weird green":    Color.from_hex("#3AE57F").rgb,
    "peacock blue":    Color.from_hex("#016795").rgb,
    "avocado green":    Color.from_hex("#87A922").rgb,
    "faded orange":    Color.from_hex("#F0944D").rgb,
    "grape purple":    Color.from_hex("#5D1451").rgb,
    "hot green":    Color.from_hex("#25FF29").rgb,
    "lime yellow":    Color.from_hex("#D0FE1D").rgb,
    "mango":    Color.from_hex("#FFA62B").rgb,
    "shamrock":    Color.from_hex("#01B44C").rgb,
    "bubblegum":    Color.from_hex("#FF6CB5").rgb,
    "purplish brown":    Color.from_hex("#6B4247").rgb,
    "vomit yellow":    Color.from_hex("#C7C10C").rgb,
    "pale cyan":    Color.from_hex("#B7FFFA").rgb,
    "key lime":    Color.from_hex("#AEFF6E").rgb,
    "tomato red":    Color.from_hex("#EC2D01").rgb,
    "lightgreen":    Color.from_hex("#76FF7B").rgb,
    "merlot":    Color.from_hex("#730039").rgb,
    "night blue":    Color.from_hex("#040348").rgb,
    "purpleish pink":    Color.from_hex("#DF4EC8").rgb,
    "apple":    Color.from_hex("#6ECB3C").rgb,
    "baby poop green":    Color.from_hex("#8F9805").rgb,
    "green apple":    Color.from_hex("#5EDC1F").rgb,
    "heliotrope":    Color.from_hex("#D94FF5").rgb,
    "yellow/green":    Color.from_hex("#C8FD3D").rgb,
    "almost black":    Color.from_hex("#070D0D").rgb,
    "cool blue":    Color.from_hex("#4984B8").rgb,
    "leafy green":    Color.from_hex("#51B73B").rgb,
    "mustard brown":    Color.from_hex("#AC7E04").rgb,
    "dusk":    Color.from_hex("#4E5481").rgb,
    "dull brown":    Color.from_hex("#876E4B").rgb,
    "frog green":    Color.from_hex("#58BC08").rgb,
    "vivid green":    Color.from_hex("#2FEF10").rgb,
    "bright light green":    Color.from_hex("#2DFE54").rgb,
    "fluro green":    Color.from_hex("#0AFF02").rgb,
    "kiwi":    Color.from_hex("#9CEF43").rgb,
    "seaweed":    Color.from_hex("#18D17B").rgb,
    "navy green":    Color.from_hex("#35530A").rgb,
    "ultramarine blue":    Color.from_hex("#1805DB").rgb,
    "iris":    Color.from_hex("#6258C4").rgb,
    "pastel orange":    Color.from_hex("#FF964F").rgb,
    "yellowish orange":    Color.from_hex("#FFAB0F").rgb,
    "perrywinkle":    Color.from_hex("#8F8CE7").rgb,
    "tealish":    Color.from_hex("#24BCA8").rgb,
    "dark plum":    Color.from_hex("#3F012C").rgb,
    "pear":    Color.from_hex("#CBF85F").rgb,
    "pinkish orange":    Color.from_hex("#FF724C").rgb,
    "midnight purple":    Color.from_hex("#280137").rgb,
    "light urple":    Color.from_hex("#B36FF6").rgb,
    "dark mint":    Color.from_hex("#48C072").rgb,
    "greenish tan":    Color.from_hex("#BCCB7A").rgb,
    "light burgundy":    Color.from_hex("#A8415B").rgb,
    "turquoise blue":    Color.from_hex("#06B1C4").rgb,
    "ugly pink":    Color.from_hex("#CD7584").rgb,
    "sandy":    Color.from_hex("#F1DA7A").rgb,
    "electric pink":    Color.from_hex("#FF0490").rgb,
    "muted purple":    Color.from_hex("#805B87").rgb,
    "mid green":    Color.from_hex("#50A747").rgb,
    "greyish":    Color.from_hex("#A8A495").rgb,
    "neon yellow":    Color.from_hex("#CFFF04").rgb,
    "banana":    Color.from_hex("#FFFF7E").rgb,
    "carnation pink":    Color.from_hex("#FF7FA7").rgb,
    "tomato":    Color.from_hex("#EF4026").rgb,
    "sea":    Color.from_hex("#3C9992").rgb,
    "muddy brown":    Color.from_hex("#886806").rgb,
    "turquoise green":    Color.from_hex("#04F489").rgb,
    "buff":    Color.from_hex("#FEF69E").rgb,
    "fawn":    Color.from_hex("#CFAF7B").rgb,
    "muted blue":    Color.from_hex("#3B719F").rgb,
    "pale rose":    Color.from_hex("#FDC1C5").rgb,
    "dark mint green":    Color.from_hex("#20C073").rgb,
    "amethyst":    Color.from_hex("#9B5FC0").rgb,
    "blue/green":    Color.from_hex("#0F9B8E").rgb,
    "chestnut":    Color.from_hex("#742802").rgb,
    "sick green":    Color.from_hex("#9DB92C").rgb,
    "pea":    Color.from_hex("#A4BF20").rgb,
    "rusty orange":    Color.from_hex("#CD5909").rgb,
    "stone":    Color.from_hex("#ADA587").rgb,
    "rose red":    Color.from_hex("#BE013C").rgb,
    "pale aqua":    Color.from_hex("#B8FFEB").rgb,
    "deep orange":    Color.from_hex("#DC4D01").rgb,
    "earth":    Color.from_hex("#A2653E").rgb,
    "mossy green":    Color.from_hex("#638B27").rgb,
    "grassy green":    Color.from_hex("#419C03").rgb,
    "pale lime green":    Color.from_hex("#B1FF65").rgb,
    "light grey blue":    Color.from_hex("#9DBCD4").rgb,
    "pale grey":    Color.from_hex("#FDFDFE").rgb,
    "asparagus":    Color.from_hex("#77AB56").rgb,
    "blueberry":    Color.from_hex("#464196").rgb,
    "purple red":    Color.from_hex("#990147").rgb,
    "pale lime":    Color.from_hex("#BEFD73").rgb,
    "greenish teal":    Color.from_hex("#32BF84").rgb,
    "caramel":    Color.from_hex("#AF6F09").rgb,
    "deep magenta":    Color.from_hex("#A0025C").rgb,
    "light peach":    Color.from_hex("#FFD8B1").rgb,
    "milk chocolate":    Color.from_hex("#7F4E1E").rgb,
    "ocher":    Color.from_hex("#BF9B0C").rgb,
    "off green":    Color.from_hex("#6BA353").rgb,
    "purply pink":    Color.from_hex("#F075E6").rgb,
    "lightblue":    Color.from_hex("#7BC8F6").rgb,
    "dusky blue":    Color.from_hex("#475F94").rgb,
    "golden":    Color.from_hex("#F5BF03").rgb,
    "light beige":    Color.from_hex("#FFFEB6").rgb,
    "butter yellow":    Color.from_hex("#FFFD74").rgb,
    "dusky purple":    Color.from_hex("#895B7B").rgb,
    "french blue":    Color.from_hex("#436BAD").rgb,
    "ugly yellow":    Color.from_hex("#D0C101").rgb,
    "greeny yellow":    Color.from_hex("#C6F808").rgb,
    "orangish red":    Color.from_hex("#F43605").rgb,
    "shamrock green":    Color.from_hex("#02C14D").rgb,
    "orangish brown":    Color.from_hex("#B25F03").rgb,
    "tree green":    Color.from_hex("#2A7E19").rgb,
    "deep violet":    Color.from_hex("#490648").rgb,
    "gunmetal":    Color.from_hex("#536267").rgb,
    "blue/purple":    Color.from_hex("#5A06EF").rgb,
    "cherry":    Color.from_hex("#CF0234").rgb,
    "sandy brown":    Color.from_hex("#C4A661").rgb,
    "warm grey":    Color.from_hex("#978A84").rgb,
    "dark indigo":    Color.from_hex("#1F0954").rgb,
    "midnight":    Color.from_hex("#03012D").rgb,
    "bluey green":    Color.from_hex("#2BB179").rgb,
    "grey pink":    Color.from_hex("#C3909B").rgb,
    "soft purple":    Color.from_hex("#A66FB5").rgb,
    "blood":    Color.from_hex("#770001").rgb,
    "brown red":    Color.from_hex("#922B05").rgb,
    "medium grey":    Color.from_hex("#7D7F7C").rgb,
    "berry":    Color.from_hex("#990F4B").rgb,
    "poo":    Color.from_hex("#8F7303").rgb,
    "purpley pink":    Color.from_hex("#C83CB9").rgb,
    "light salmon":    Color.from_hex("#FEA993").rgb,
    "snot":    Color.from_hex("#ACBB0D").rgb,
    "easter purple":    Color.from_hex("#C071FE").rgb,
    "light yellow green":    Color.from_hex("#CCFD7F").rgb,
    "dark navy blue":    Color.from_hex("#00022E").rgb,
    "drab":    Color.from_hex("#828344").rgb,
    "light rose":    Color.from_hex("#FFC5CB").rgb,
    "rouge":    Color.from_hex("#AB1239").rgb,
    "purplish red":    Color.from_hex("#B0054B").rgb,
    "slime green":    Color.from_hex("#99CC04").rgb,
    "baby poop":    Color.from_hex("#937C00").rgb,
    "irish green":    Color.from_hex("#019529").rgb,
    "pink/purple":    Color.from_hex("#EF1DE7").rgb,
    "dark navy":    Color.from_hex("#000435").rgb,
    "greeny blue":    Color.from_hex("#42B395").rgb,
    "light plum":    Color.from_hex("#9D5783").rgb,
    "pinkish grey":    Color.from_hex("#C8ACA9").rgb,
    "dirty orange":    Color.from_hex("#C87606").rgb,
    "rust red":    Color.from_hex("#AA2704").rgb,
    "pale lilac":    Color.from_hex("#E4CBFF").rgb,
    "orangey red":    Color.from_hex("#FA4224").rgb,
    "primary blue":    Color.from_hex("#0804F9").rgb,
    "kermit green":    Color.from_hex("#5CB200").rgb,
    "brownish purple":    Color.from_hex("#76424E").rgb,
    "murky green":    Color.from_hex("#6C7A0E").rgb,
    "wheat":    Color.from_hex("#FBDD7E").rgb,
    "very dark purple":    Color.from_hex("#2A0134").rgb,
    "bottle green":    Color.from_hex("#044A05").rgb,
    "watermelon":    Color.from_hex("#FD4659").rgb,
    "deep sky blue":    Color.from_hex("#0D75F8").rgb,
    "fire engine red":    Color.from_hex("#FE0002").rgb,
    "yellow ochre":    Color.from_hex("#CB9D06").rgb,
    "pumpkin orange":    Color.from_hex("#FB7D07").rgb,
    "pale olive":    Color.from_hex("#B9CC81").rgb,
    "light lilac":    Color.from_hex("#EDC8FF").rgb,
    "lightish green":    Color.from_hex("#61E160").rgb,
    "carolina blue":    Color.from_hex("#8AB8FE").rgb,
    "mulberry":    Color.from_hex("#920A4E").rgb,
    "shocking pink":    Color.from_hex("#FE02A2").rgb,
    "auburn":    Color.from_hex("#9A3001").rgb,
    "bright lime green":    Color.from_hex("#65FE08").rgb,
    "celadon":    Color.from_hex("#BEFDB7").rgb,
    "pinkish brown":    Color.from_hex("#B17261").rgb,
    "poo brown":    Color.from_hex("#885F01").rgb,
    "bright sky blue":    Color.from_hex("#02CCFE").rgb,
    "celery":    Color.from_hex("#C1FD95").rgb,
    "dirt brown":    Color.from_hex("#836539").rgb,
    "strawberry":    Color.from_hex("#FB2943").rgb,
    "dark lime":    Color.from_hex("#84B701").rgb,
    "copper":    Color.from_hex("#B66325").rgb,
    "medium brown":    Color.from_hex("#7F5112").rgb,
    "muted green":    Color.from_hex("#5FA052").rgb,
    "robin's egg":    Color.from_hex("#6DEDFD").rgb,
    "bright aqua":    Color.from_hex("#0BF9EA").rgb,
    "bright lavender":    Color.from_hex("#C760FF").rgb,
    "ivory":    Color.from_hex("#FFFFCB").rgb,
    "very light purple":    Color.from_hex("#F6CEFC").rgb,
    "light navy":    Color.from_hex("#155084").rgb,
    "pink red":    Color.from_hex("#F5054F").rgb,
    "olive brown":    Color.from_hex("#645403").rgb,
    "poop brown":    Color.from_hex("#7A5901").rgb,
    "mustard green":    Color.from_hex("#A8B504").rgb,
    "ocean green":    Color.from_hex("#3D9973").rgb,
    "very dark blue":    Color.from_hex("#000133").rgb,
    "dusty green":    Color.from_hex("#76A973").rgb,
    "light navy blue":    Color.from_hex("#2E5A88").rgb,
    "minty green":    Color.from_hex("#0BF77D").rgb,
    "adobe":    Color.from_hex("#BD6C48").rgb,
    "barney":    Color.from_hex("#AC1DB8").rgb,
    "jade green":    Color.from_hex("#2BAF6A").rgb,
    "bright light blue":    Color.from_hex("#26F7FD").rgb,
    "light lime":    Color.from_hex("#AEFD6C").rgb,
    "dark khaki":    Color.from_hex("#9B8F55").rgb,
    "orange yellow":    Color.from_hex("#FFAD01").rgb,
    "ocre":    Color.from_hex("#C69C04").rgb,
    "maize":    Color.from_hex("#F4D054").rgb,
    "faded pink":    Color.from_hex("#DE9DAC").rgb,
    "british racing green":    Color.from_hex("#05480D").rgb,
    "sandstone":    Color.from_hex("#C9AE74").rgb,
    "mud brown":    Color.from_hex("#60460F").rgb,
    "light sea green":    Color.from_hex("#98F6B0").rgb,
    "robin egg blue":    Color.from_hex("#8AF1FE").rgb,
    "aqua marine":    Color.from_hex("#2EE8BB").rgb,
    "dark sea green":    Color.from_hex("#11875D").rgb,
    "soft pink":    Color.from_hex("#FDB0C0").rgb,
    "orangey brown":    Color.from_hex("#B16002").rgb,
    "cherry red":    Color.from_hex("#F7022A").rgb,
    "burnt yellow":    Color.from_hex("#D5AB09").rgb,
    "brownish grey":    Color.from_hex("#86775F").rgb,
    "camel":    Color.from_hex("#C69F59").rgb,
    "purplish grey":    Color.from_hex("#7A687F").rgb,
    "marine":    Color.from_hex("#042E60").rgb,
    "greyish pink":    Color.from_hex("#C88D94").rgb,
    "pale turquoise":    Color.from_hex("#A5FBD5").rgb,
    "pastel yellow":    Color.from_hex("#FFFE71").rgb,
    "bluey purple":    Color.from_hex("#6241C7").rgb,
    "canary yellow":    Color.from_hex("#FFFE40").rgb,
    "faded red":    Color.from_hex("#D3494E").rgb,
    "sepia":    Color.from_hex("#985E2B").rgb,
    "coffee":    Color.from_hex("#A6814C").rgb,
    "bright magenta":    Color.from_hex("#FF08E8").rgb,
    "mocha":    Color.from_hex("#9D7651").rgb,
    "ecru":    Color.from_hex("#FEFFCA").rgb,
    "purpleish":    Color.from_hex("#98568D").rgb,
    "cranberry":    Color.from_hex("#9E003A").rgb,
    "darkish green":    Color.from_hex("#287C37").rgb,
    "brown orange":    Color.from_hex("#B96902").rgb,
    "dusky rose":    Color.from_hex("#BA6873").rgb,
    "melon":    Color.from_hex("#FF7855").rgb,
    "sickly green":    Color.from_hex("#94B21C").rgb,
    "silver":    Color.from_hex("#C5C9C7").rgb,
    "purply blue":    Color.from_hex("#661AEE").rgb,
    "purpleish blue":    Color.from_hex("#6140EF").rgb,
    "hospital green":    Color.from_hex("#9BE5AA").rgb,
    "shit brown":    Color.from_hex("#7B5804").rgb,
    "mid blue":    Color.from_hex("#276AB3").rgb,
    "amber":    Color.from_hex("#FEB308").rgb,
    "easter green":    Color.from_hex("#8CFD7E").rgb,
    "soft blue":    Color.from_hex("#6488EA").rgb,
    "cerulean blue":    Color.from_hex("#056EEE").rgb,
    "golden brown":    Color.from_hex("#B27A01").rgb,
    "bright turquoise":    Color.from_hex("#0FFEF9").rgb,
    "red pink":    Color.from_hex("#FA2A55").rgb,
    "red purple":    Color.from_hex("#820747").rgb,
    "greyish brown":    Color.from_hex("#7A6A4F").rgb,
    "vermillion":    Color.from_hex("#F4320C").rgb,
    "russet":    Color.from_hex("#A13905").rgb,
    "steel grey":    Color.from_hex("#6F828A").rgb,
    "lighter purple":    Color.from_hex("#A55AF4").rgb,
    "bright violet":    Color.from_hex("#AD0AFD").rgb,
    "prussian blue":    Color.from_hex("#004577").rgb,
    "slate green":    Color.from_hex("#658D6D").rgb,
    "dirty pink":    Color.from_hex("#CA7B80").rgb,
    "dark blue green":    Color.from_hex("#005249").rgb,
    "pine":    Color.from_hex("#2B5D34").rgb,
    "yellowy green":    Color.from_hex("#BFF128").rgb,
    "dark gold":    Color.from_hex("#B59410").rgb,
    "bluish":    Color.from_hex("#2976BB").rgb,
    "darkish blue":    Color.from_hex("#014182").rgb,
    "dull red":    Color.from_hex("#BB3F3F").rgb,
    "pinky red":    Color.from_hex("#FC2647").rgb,
    "bronze":    Color.from_hex("#A87900").rgb,
    "pale teal":    Color.from_hex("#82CBB2").rgb,
    "military green":    Color.from_hex("#667C3E").rgb,
    "barbie pink":    Color.from_hex("#FE46A5").rgb,
    "bubblegum pink":    Color.from_hex("#FE83CC").rgb,
    "pea soup green":    Color.from_hex("#94A617").rgb,
    "dark mustard":    Color.from_hex("#A88905").rgb,
    "shit":    Color.from_hex("#7F5F00").rgb,
    "medium purple":    Color.from_hex("#9E43A2").rgb,
    "very dark green":    Color.from_hex("#062E03").rgb,
    "dirt":    Color.from_hex("#8A6E45").rgb,
    "dusky pink":    Color.from_hex("#CC7A8B").rgb,
    "red violet":    Color.from_hex("#9E0168").rgb,
    "lemon yellow":    Color.from_hex("#FDFF38").rgb,
    "pistachio":    Color.from_hex("#C0FA8B").rgb,
    "dull yellow":    Color.from_hex("#EEDC5B").rgb,
    "dark lime green":    Color.from_hex("#7EBD01").rgb,
    "denim blue":    Color.from_hex("#3B5B92").rgb,
    "teal blue":    Color.from_hex("#01889F").rgb,
    "lightish blue":    Color.from_hex("#3D7AFD").rgb,
    "purpley blue":    Color.from_hex("#5F34E7").rgb,
    "light indigo":    Color.from_hex("#6D5ACF").rgb,
    "swamp green":    Color.from_hex("#748500").rgb,
    "brown green":    Color.from_hex("#706C11").rgb,
    "dark maroon":    Color.from_hex("#3C0008").rgb,
    "hot purple":    Color.from_hex("#CB00F5").rgb,
    "dark forest green":    Color.from_hex("#002D04").rgb,
    "faded blue":    Color.from_hex("#658CBB").rgb,
    "drab green":    Color.from_hex("#749551").rgb,
    "light lime green":    Color.from_hex("#B9FF66").rgb,
    "snot green":    Color.from_hex("#9DC100").rgb,
    "yellowish":    Color.from_hex("#FAEE66").rgb,
    "light blue green":    Color.from_hex("#7EFBB3").rgb,
    "bordeaux":    Color.from_hex("#7B002C").rgb,
    "light mauve":    Color.from_hex("#C292A1").rgb,
    "ocean":    Color.from_hex("#017B92").rgb,
    "marigold":    Color.from_hex("#FCC006").rgb,
    "muddy green":    Color.from_hex("#657432").rgb,
    "dull orange":    Color.from_hex("#D8863B").rgb,
    "steel":    Color.from_hex("#738595").rgb,
    "electric purple":    Color.from_hex("#AA23FF").rgb,
    "fluorescent green":    Color.from_hex("#08FF08").rgb,
    "yellowish brown":    Color.from_hex("#9B7A01").rgb,
    "blush":    Color.from_hex("#F29E8E").rgb,
    "soft green":    Color.from_hex("#6FC276").rgb,
    "bright orange":    Color.from_hex("#FF5B00").rgb,
    "lemon":    Color.from_hex("#FDFF52").rgb,
    "purple grey":    Color.from_hex("#866F85").rgb,
    "acid green":    Color.from_hex("#8FFE09").rgb,
    "pale lavender":    Color.from_hex("#EECFFE").rgb,
    "violet blue":    Color.from_hex("#510AC9").rgb,
    "light forest green":    Color.from_hex("#4F9153").rgb,
    "burnt red":    Color.from_hex("#9F2305").rgb,
    "khaki green":    Color.from_hex("#728639").rgb,
    "cerise":    Color.from_hex("#DE0C62").rgb,
    "faded purple":    Color.from_hex("#916E99").rgb,
    "apricot":    Color.from_hex("#FFB16D").rgb,
    "dark olive green":    Color.from_hex("#3C4D03").rgb,
    "grey brown":    Color.from_hex("#7F7053").rgb,
    "green grey":    Color.from_hex("#77926F").rgb,
    "true blue":    Color.from_hex("#010FCC").rgb,
    "pale violet":    Color.from_hex("#CEAEFA").rgb,
    "periwinkle blue":    Color.from_hex("#8F99FB").rgb,
    "light sky blue":    Color.from_hex("#C6FCFF").rgb,
    "blurple":    Color.from_hex("#5539CC").rgb,
    "green brown":    Color.from_hex("#544E03").rgb,
    "bluegreen":    Color.from_hex("#017A79").rgb,
    "bright teal":    Color.from_hex("#01F9C6").rgb,
    "brownish yellow":    Color.from_hex("#C9B003").rgb,
    "pea soup":    Color.from_hex("#929901").rgb,
    "forest":    Color.from_hex("#0B5509").rgb,
    "barney purple":    Color.from_hex("#A00498").rgb,
    "ultramarine":    Color.from_hex("#2000B1").rgb,
    "purplish":    Color.from_hex("#94568C").rgb,
    "puke yellow":    Color.from_hex("#C2BE0E").rgb,
    "bluish grey":    Color.from_hex("#748B97").rgb,
    "dark periwinkle":    Color.from_hex("#665FD1").rgb,
    "dark lilac":    Color.from_hex("#9C6DA5").rgb,
    "reddish":    Color.from_hex("#C44240").rgb,
    "light maroon":    Color.from_hex("#A24857").rgb,
    "dusty purple":    Color.from_hex("#825F87").rgb,
    "terra cotta":    Color.from_hex("#C9643B").rgb,
    "avocado":    Color.from_hex("#90B134").rgb,
    "marine blue":    Color.from_hex("#01386A").rgb,
    "teal green":    Color.from_hex("#25A36F").rgb,
    "slate grey":    Color.from_hex("#59656D").rgb,
    "lighter green":    Color.from_hex("#75FD63").rgb,
    "electric green":    Color.from_hex("#21FC0D").rgb,
    "dusty blue":    Color.from_hex("#5A86AD").rgb,
    "golden yellow":    Color.from_hex("#FEC615").rgb,
    "bright yellow":    Color.from_hex("#FFFD01").rgb,
    "light lavender":    Color.from_hex("#DFC5FE").rgb,
    "umber":    Color.from_hex("#B26400").rgb,
    "poop":    Color.from_hex("#7F5E00").rgb,
    "dark peach":    Color.from_hex("#DE7E5D").rgb,
    "jungle green":    Color.from_hex("#048243").rgb,
    "eggshell":    Color.from_hex("#FFFFD4").rgb,
    "denim":    Color.from_hex("#3B638C").rgb,
    "yellow brown":    Color.from_hex("#B79400").rgb,
    "dull purple":    Color.from_hex("#84597E").rgb,
    "chocolate brown":    Color.from_hex("#411900").rgb,
    "wine red":    Color.from_hex("#7B0323").rgb,
    "neon blue":    Color.from_hex("#04D9FF").rgb,
    "dirty green":    Color.from_hex("#667E2C").rgb,
    "light tan":    Color.from_hex("#FBEEAC").rgb,
    "ice blue":    Color.from_hex("#D7FFFE").rgb,
    "cadet blue":    Color.from_hex("#4E7496").rgb,
    "dark mauve":    Color.from_hex("#874C62").rgb,
    "very light blue":    Color.from_hex("#D5FFFF").rgb,
    "grey purple":    Color.from_hex("#826D8C").rgb,
    "pastel pink":    Color.from_hex("#FFBACD").rgb,
    "very light green":    Color.from_hex("#D1FFBD").rgb,
    "dark sky blue":    Color.from_hex("#448EE4").rgb,
    "evergreen":    Color.from_hex("#05472A").rgb,
    "dull pink":    Color.from_hex("#D5869D").rgb,
    "aubergine":    Color.from_hex("#3D0734").rgb,
    "mahogany":    Color.from_hex("#4A0100").rgb,
    "reddish orange":    Color.from_hex("#F8481C").rgb,
    "deep green":    Color.from_hex("#02590F").rgb,
    "vomit green":    Color.from_hex("#89A203").rgb,
    "purple pink":    Color.from_hex("#E03FD8").rgb,
    "dusty pink":    Color.from_hex("#D58A94").rgb,
    "faded green":    Color.from_hex("#7BB274").rgb,
    "camo green":    Color.from_hex("#526525").rgb,
    "pinky purple":    Color.from_hex("#C94CBE").rgb,
    "pink purple":    Color.from_hex("#DB4BDA").rgb,
    "brownish red":    Color.from_hex("#9E3623").rgb,
    "dark rose":    Color.from_hex("#B5485D").rgb,
    "mud":    Color.from_hex("#735C12").rgb,
    "brownish":    Color.from_hex("#9C6D57").rgb,
    "emerald green":    Color.from_hex("#028F1E").rgb,
    "pale brown":    Color.from_hex("#B1916E").rgb,
    "dull blue":    Color.from_hex("#49759C").rgb,
    "burnt umber":    Color.from_hex("#A0450E").rgb,
    "medium green":    Color.from_hex("#39AD48").rgb,
    "clay":    Color.from_hex("#B66A50").rgb,
    "light aqua":    Color.from_hex("#8CFFDB").rgb,
    "light olive green":    Color.from_hex("#A4BE5C").rgb,
    "brownish orange":    Color.from_hex("#CB7723").rgb,
    "dark aqua":    Color.from_hex("#05696B").rgb,
    "purplish pink":    Color.from_hex("#CE5DAE").rgb,
    "dark salmon":    Color.from_hex("#C85A53").rgb,
    "greenish grey":    Color.from_hex("#96AE8D").rgb,
    "jade":    Color.from_hex("#1FA774").rgb,
    "ugly green":    Color.from_hex("#7A9703").rgb,
    "dark beige":    Color.from_hex("#AC9362").rgb,
    "emerald":    Color.from_hex("#01A049").rgb,
    "pale red":    Color.from_hex("#D9544D").rgb,
    "light magenta":    Color.from_hex("#FA5FF7").rgb,
    "sky":    Color.from_hex("#82CAFC").rgb,
    "light cyan":    Color.from_hex("#ACFFFC").rgb,
    "yellow orange":    Color.from_hex("#FCB001").rgb,
    "reddish purple":    Color.from_hex("#910951").rgb,
    "reddish pink":    Color.from_hex("#FE2C54").rgb,
    "orchid":    Color.from_hex("#C875C4").rgb,
    "dirty yellow":    Color.from_hex("#CDC50A").rgb,
    "orange red":    Color.from_hex("#FD411E").rgb,
    "deep red":    Color.from_hex("#9A0200").rgb,
    "orange brown":    Color.from_hex("#BE6400").rgb,
    "cobalt blue":    Color.from_hex("#030AA7").rgb,
    "neon pink":    Color.from_hex("#FE019A").rgb,
    "rose pink":    Color.from_hex("#F7879A").rgb,
    "greyish purple":    Color.from_hex("#887191").rgb,
    "raspberry":    Color.from_hex("#B00149").rgb,
    "aqua green":    Color.from_hex("#12E193").rgb,
    "salmon pink":    Color.from_hex("#FE7B7C").rgb,
    "tangerine":    Color.from_hex("#FF9408").rgb,
    "brownish green":    Color.from_hex("#6A6E09").rgb,
    "red brown":    Color.from_hex("#8B2E16").rgb,
    "greenish brown":    Color.from_hex("#696112").rgb,
    "pumpkin":    Color.from_hex("#E17701").rgb,
    "pine green":    Color.from_hex("#0A481E").rgb,
    "charcoal":    Color.from_hex("#343837").rgb,
    "baby pink":    Color.from_hex("#FFB7CE").rgb,
    "cornflower":    Color.from_hex("#6A79F7").rgb,
    "blue violet":    Color.from_hex("#5D06E9").rgb,
    "chocolate":    Color.from_hex("#3D1C02").rgb,
    "greyish green":    Color.from_hex("#82A67D").rgb,
    "scarlet":    Color.from_hex("#BE0119").rgb,
    "green yellow":    Color.from_hex("#C9FF27").rgb,
    "dark olive":    Color.from_hex("#373E02").rgb,
    "sienna":    Color.from_hex("#A9561E").rgb,
    "pastel purple":    Color.from_hex("#CAA0FF").rgb,
    "terracotta":    Color.from_hex("#CA6641").rgb,
    "aqua blue":    Color.from_hex("#02D8E9").rgb,
    "sage green":    Color.from_hex("#88B378").rgb,
    "blood red":    Color.from_hex("#980002").rgb,
    "deep pink":    Color.from_hex("#CB0162").rgb,
    "grass":    Color.from_hex("#5CAC2D").rgb,
    "moss":    Color.from_hex("#769958").rgb,
    "pastel blue":    Color.from_hex("#A2BFFE").rgb,
    "bluish green":    Color.from_hex("#10A674").rgb,
    "green blue":    Color.from_hex("#06B48B").rgb,
    "dark tan":    Color.from_hex("#AF884A").rgb,
    "greenish blue":    Color.from_hex("#0B8B87").rgb,
    "pale orange":    Color.from_hex("#FFA756").rgb,
    "vomit":    Color.from_hex("#A2A415").rgb,
    "forrest green":    Color.from_hex("#154406").rgb,
    "dark lavender":    Color.from_hex("#856798").rgb,
    "dark violet":    Color.from_hex("#34013F").rgb,
    "purple blue":    Color.from_hex("#632DE9").rgb,
    "dark cyan":    Color.from_hex("#0A888A").rgb,
    "olive drab":    Color.from_hex("#6F7632").rgb,
    "pinkish":    Color.from_hex("#D46A7E").rgb,
    "cobalt":    Color.from_hex("#1E488F").rgb,
    "neon purple":    Color.from_hex("#BC13FE").rgb,
    "light turquoise":    Color.from_hex("#7EF4CC").rgb,
    "apple green":    Color.from_hex("#76CD26").rgb,
    "dull green":    Color.from_hex("#74A662").rgb,
    "wine":    Color.from_hex("#80013F").rgb,
    "powder blue":    Color.from_hex("#B1D1FC").rgb,
    "off white":    Color.from_hex("#FFFFE4").rgb,
    "electric blue":    Color.from_hex("#0652FF").rgb,
    "dark turquoise":    Color.from_hex("#045C5A").rgb,
    "blue purple":    Color.from_hex("#5729CE").rgb,
    "azure":    Color.from_hex("#069AF3").rgb,
    "bright red":    Color.from_hex("#FF000D").rgb,
    "pinkish red":    Color.from_hex("#F10C45").rgb,
    "cornflower blue":    Color.from_hex("#5170D7").rgb,
    "light olive":    Color.from_hex("#ACBF69").rgb,
    "grape":    Color.from_hex("#6C3461").rgb,
    "greyish blue":    Color.from_hex("#5E819D").rgb,
    "purplish blue":    Color.from_hex("#601EF9").rgb,
    "yellowish green":    Color.from_hex("#B0DD16").rgb,
    "greenish yellow":    Color.from_hex("#CDFD02").rgb,
    "medium blue":    Color.from_hex("#2C6FBB").rgb,
    "dusty rose":    Color.from_hex("#C0737A").rgb,
    "light violet":    Color.from_hex("#D6B4FC").rgb,
    "midnight blue":    Color.from_hex("#020035").rgb,
    "bluish purple":    Color.from_hex("#703BE7").rgb,
    "red orange":    Color.from_hex("#FD3C06").rgb,
    "dark magenta":    Color.from_hex("#960056").rgb,
    "greenish":    Color.from_hex("#40A368").rgb,
    "ocean blue":    Color.from_hex("#03719C").rgb,
    "coral":    Color.from_hex("#FC5A50").rgb,
    "cream":    Color.from_hex("#FFFFC2").rgb,
    "reddish brown":    Color.from_hex("#7F2B0A").rgb,
    "burnt sienna":    Color.from_hex("#B04E0F").rgb,
    "brick":    Color.from_hex("#A03623").rgb,
    "sage":    Color.from_hex("#87AE73").rgb,
    "grey green":    Color.from_hex("#789B73").rgb,
    "white":    Color.from_hex("#FFFFFF").rgb,
    "robin's egg blue":    Color.from_hex("#98EFF9").rgb,
    "moss green":    Color.from_hex("#658B38").rgb,
    "steel blue":    Color.from_hex("#5A7D9A").rgb,
    "eggplant":    Color.from_hex("#380835").rgb,
    "light yellow":    Color.from_hex("#FFFE7A").rgb,
    "leaf green":    Color.from_hex("#5CA904").rgb,
    "light grey":    Color.from_hex("#D8DCD6").rgb,
    "puke":    Color.from_hex("#A5A502").rgb,
    "pinkish purple":    Color.from_hex("#D648D7").rgb,
    "sea blue":    Color.from_hex("#047495").rgb,
    "pale purple":    Color.from_hex("#B790D4").rgb,
    "slate blue":    Color.from_hex("#5B7C99").rgb,
    "blue grey":    Color.from_hex("#607C8E").rgb,
    "hunter green":    Color.from_hex("#0B4008").rgb,
    "fuchsia":    Color.from_hex("#ED0DD9").rgb,
    "crimson":    Color.from_hex("#8C000F").rgb,
    "pale yellow":    Color.from_hex("#FFFF84").rgb,
    "ochre":    Color.from_hex("#BF9005").rgb,
    "mustard yellow":    Color.from_hex("#D2BD0A").rgb,
    "light red":    Color.from_hex("#FF474C").rgb,
    "cerulean":    Color.from_hex("#0485D1").rgb,
    "pale pink":    Color.from_hex("#FFCFDC").rgb,
    "deep blue":    Color.from_hex("#040273").rgb,
    "rust":    Color.from_hex("#A83C09").rgb,
    "light teal":    Color.from_hex("#90E4C1").rgb,
    "slate":    Color.from_hex("#516572").rgb,
    "goldenrod":    Color.from_hex("#FAC205").rgb,
    "dark yellow":    Color.from_hex("#D5B60A").rgb,
    "dark grey":    Color.from_hex("#363737").rgb,
    "army green":    Color.from_hex("#4B5D16").rgb,
    "grey blue":    Color.from_hex("#6B8BA4").rgb,
    "seafoam":    Color.from_hex("#80F9AD").rgb,
    "puce":    Color.from_hex("#A57E52").rgb,
    "spring green":    Color.from_hex("#A9F971").rgb,
    "dark orange":    Color.from_hex("#C65102").rgb,
    "sand":    Color.from_hex("#E2CA76").rgb,
    "pastel green":    Color.from_hex("#B0FF9D").rgb,
    "mint":    Color.from_hex("#9FFEB0").rgb,
    "light orange":    Color.from_hex("#FDAA48").rgb,
    "bright pink":    Color.from_hex("#FE01B1").rgb,
    "chartreuse":    Color.from_hex("#C1F80A").rgb,
    "deep purple":    Color.from_hex("#36013F").rgb,
    "dark brown":    Color.from_hex("#341C02").rgb,
    "taupe":    Color.from_hex("#B9A281").rgb,
    "pea green":    Color.from_hex("#8EAB12").rgb,
    "puke green":    Color.from_hex("#9AAE07").rgb,
    "kelly green":    Color.from_hex("#02AB2E").rgb,
    "seafoam green":    Color.from_hex("#7AF9AB").rgb,
    "blue green":    Color.from_hex("#137E6D").rgb,
    "khaki":    Color.from_hex("#AAA662").rgb,
    "burgundy":    Color.from_hex("#610023").rgb,
    "dark teal":    Color.from_hex("#014D4E").rgb,
    "brick red":    Color.from_hex("#8F1402").rgb,
    "royal purple":    Color.from_hex("#4B006E").rgb,
    "plum":    Color.from_hex("#580F41").rgb,
    "mint green":    Color.from_hex("#8FFF9F").rgb,
    "gold":    Color.from_hex("#DBB40C").rgb,
    "baby blue":    Color.from_hex("#A2CFFE").rgb,
    "yellow green":    Color.from_hex("#C0FB2D").rgb,
    "bright purple":    Color.from_hex("#BE03FD").rgb,
    "dark red":    Color.from_hex("#840000").rgb,
    "pale blue":    Color.from_hex("#D0FEFE").rgb,
    "grass green":    Color.from_hex("#3F9B0B").rgb,
    "navy":    Color.from_hex("#01153E").rgb,
    "aquamarine":    Color.from_hex("#04D8B2").rgb,
    "burnt orange":    Color.from_hex("#C04E01").rgb,
    "neon green":    Color.from_hex("#0CFF0C").rgb,
    "bright blue":    Color.from_hex("#0165FC").rgb,
    "rose":    Color.from_hex("#CF6275").rgb,
    "light pink":    Color.from_hex("#FFD1DF").rgb,
    "mustard":    Color.from_hex("#CEB301").rgb,
    "indigo":    Color.from_hex("#380282").rgb,
    "lime":    Color.from_hex("#AAFF32").rgb,
    "sea green":    Color.from_hex("#53FCA1").rgb,
    "periwinkle":    Color.from_hex("#8E82FE").rgb,
    "dark pink":    Color.from_hex("#CB416B").rgb,
    "olive green":    Color.from_hex("#677A04").rgb,
    "peach":    Color.from_hex("#FFB07C").rgb,
    "pale green":    Color.from_hex("#C7FDB5").rgb,
    "light brown":    Color.from_hex("#AD8150").rgb,
    "hot pink":    Color.from_hex("#FF028D").rgb,
    "black":    Color.from_hex("#000000").rgb,
    "lilac":    Color.from_hex("#CEA2FD").rgb,
    "navy blue":    Color.from_hex("#001146").rgb,
    "royal blue":    Color.from_hex("#0504AA").rgb,
    "beige":    Color.from_hex("#E6DAA6").rgb,
    "salmon":    Color.from_hex("#FF796C").rgb,
    "olive":    Color.from_hex("#6E750E").rgb,
    "maroon":    Color.from_hex("#650021").rgb,
    "bright green":    Color.from_hex("#01FF07").rgb,
    "dark purple":    Color.from_hex("#35063E").rgb,
    "mauve":    Color.from_hex("#AE7181").rgb,
    "forest green":    Color.from_hex("#06470C").rgb,
    "aqua":    Color.from_hex("#13EAC9").rgb,
    "cyan":    Color.from_hex("#00FFFF").rgb,
    "tan":    Color.from_hex("#D1B26F").rgb,
    "dark blue":    Color.from_hex("#00035B").rgb,
    "lavender":    Color.from_hex("#C79FEF").rgb,
    "turquoise":    Color.from_hex("#06C2AC").rgb,
    "dark green":    Color.from_hex("#033500").rgb,
    "violet":    Color.from_hex("#9A0EEA").rgb,
    "light purple":    Color.from_hex("#BF77F6").rgb,
    "lime green":    Color.from_hex("#89FE05").rgb,
    "grey":    Color.from_hex("#929591").rgb,
    "sky blue":    Color.from_hex("#75BBFD").rgb,
    "yellow":    Color.from_hex("#FFFF14").rgb,
    "magenta":    Color.from_hex("#C20078").rgb,
    "light green":    Color.from_hex("#96F97B").rgb,
    "orange":    Color.from_hex("#F97306").rgb,
    "teal":    Color.from_hex("#029386").rgb,
    "light blue":    Color.from_hex("#95D0FC").rgb,
    "red":    Color.from_hex("#E50000").rgb,
    "brown":    Color.from_hex("#653700").rgb,
    "pink":    Color.from_hex("#FF81C0").rgb,
    "blue":    Color.from_hex("#0343DF").rgb,
    "green":    Color.from_hex("#15B01A").rgb,
    "purple":    Color.from_hex("#7E1E9C").rgb
}


# selection of 48 colors from xkcd palette
# (those are colors published directly on mentioned article)
XKCD_48_PALETTE = {
    "light pink":    Color.from_hex("#FFD1DF").rgb,
    "mustard":    Color.from_hex("#CEB301").rgb,
    "indigo":    Color.from_hex("#380282").rgb,
    "lime":    Color.from_hex("#AAFF32").rgb,
    "sea green":    Color.from_hex("#53FCA1").rgb,
    "periwinkle":    Color.from_hex("#8E82FE").rgb,
    "dark pink":    Color.from_hex("#CB416B").rgb,
    "olive green":    Color.from_hex("#677A04").rgb,
    "peach":    Color.from_hex("#FFB07C").rgb,
    "pale green":    Color.from_hex("#C7FDB5").rgb,
    "light brown":    Color.from_hex("#AD8150").rgb,
    "hot pink":    Color.from_hex("#FF028D").rgb,
    "black":    Color.from_hex("#000000").rgb,
    "lilac":    Color.from_hex("#CEA2FD").rgb,
    "navy blue":    Color.from_hex("#001146").rgb,
    "royal blue":    Color.from_hex("#0504AA").rgb,
    "beige":    Color.from_hex("#E6DAA6").rgb,
    "salmon":    Color.from_hex("#FF796C").rgb,
    "olive":    Color.from_hex("#6E750E").rgb,
    "maroon":    Color.from_hex("#650021").rgb,
    "bright green":    Color.from_hex("#01FF07").rgb,
    "dark purple":    Color.from_hex("#35063E").rgb,
    "mauve":    Color.from_hex("#AE7181").rgb,
    "forest green":    Color.from_hex("#06470C").rgb,
    "aqua":    Color.from_hex("#13EAC9").rgb,
    "cyan":    Color.from_hex("#00FFFF").rgb,
    "tan":    Color.from_hex("#D1B26F").rgb,
    "dark blue":    Color.from_hex("#00035B").rgb,
    "lavender":    Color.from_hex("#C79FEF").rgb,
    "turquoise":    Color.from_hex("#06C2AC").rgb,
    "dark green":    Color.from_hex("#033500").rgb,
    "violet":    Color.from_hex("#9A0EEA").rgb,
    "light purple":    Color.from_hex("#BF77F6").rgb,
    "lime green":    Color.from_hex("#89FE05").rgb,
    "grey":    Color.from_hex("#929591").rgb,
    "sky blue":    Color.from_hex("#75BBFD").rgb,
    "yellow":    Color.from_hex("#FFFF14").rgb,
    "magenta":    Color.from_hex("#C20078").rgb,
    "light green":    Color.from_hex("#96F97B").rgb,
    "orange":    Color.from_hex("#F97306").rgb,
    "teal":    Color.from_hex("#029386").rgb,
    "light blue":    Color.from_hex("#95D0FC").rgb,
    "red":    Color.from_hex("#E50000").rgb,
    "brown":    Color.from_hex("#653700").rgb,
    "pink":    Color.from_hex("#FF81C0").rgb,
    "blue":    Color.from_hex("#0343DF").rgb,
    "green":    Color.from_hex("#15B01A").rgb,
    "purple":    Color.from_hex("#7E1E9C").rgb
}

# all available palettes
PALETTES = {
    "web": WEB_PALETTE,
    "xkcd_full": XKCD_FULL_PALETTE,
    "xkcd_48": XKCD_48_PALETTE
}


class PaletteColorsCounter(dict):

    @staticmethod
    def from_palette(palette):
        return PaletteColorsCounter(**{k:0 for k in palette.keys()})